<a href="https://colab.research.google.com/github/mjwillis717-coder/dsrp/blob/main/DSRP_Education.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import csv
import pandas as pd

In [3]:
college_csv = '/content/College_Scorecard_Cleaned.csv'
college_df = pd.read_csv(college_csv)
college_df.head()

,UNITID,INSTNM,STABBR,REGION,LOCALE,CONTROL,ADM_RATE,SAT_AVG,ACTCMMID,UGDS,COSTT4_A,TUITIONFEE_IN,TUITIONFEE_OUT,PCTPELL,PCTFLOAN,RET_FT4,C150_4,GRAD_DEBT_MDN,MD_EARN_WNE_4YR,MD_EARN_WNE_P10
0,100654,Alabama A & M University,AL,5,12.0,1,0.5795,938.0,18.0,6124.0,27153.0,10024.0,18634.0,0.6298,0.7454,0.6989,0.2403,31000.0,54018.0,40628.0
1,100663,University of Alabama at Birmingham,AL,5,12.0,1,0.8818,1258.0,27.0,11635.0,28145.0,9098.0,22562.0,0.3402,0.4027,0.8009,0.6423,22300.0,64969.0,54501.0
2,100690,Amridge University,AL,5,12.0,2,NaN,NaN,NaN,241.0,NaN,7590.0,7590.0,0.7655,0.8097,NaN,1.0000,32189.0,50075.0,37621.0
3,100706,University of Alabama in Huntsville,AL,5,12.0,1,0.6857,1319.0,28.0,6591.0,27392.0,12132.0,26408.0,0.2464,0.3255,0.8425,0.6429,20705.0,81045.0,61767.0
4,100724,Alabama State University,AL,5,12.0,1,0.9755,976.0,18.0,3477.0,23586.0,11248.0,19576.0,0.7134,0.7420,0.6975,0.3034,31000.0,45998.0,34502.0

In [4]:
college_df.columns

Index(['UNITID', 'INSTNM', 'STABBR', 'REGION', 'LOCALE', 'CONTROL', 'ADM_RATE',
       'SAT_AVG', 'ACTCMMID', 'UGDS', 'COSTT4_A', 'TUITIONFEE_IN',
       'TUITIONFEE_OUT', 'PCTPELL', 'PCTFLOAN', 'RET_FT4', 'C150_4',
       'GRAD_DEBT_MDN', 'MD_EARN_WNE_4YR', 'MD_EARN_WNE_P10'],
      dtype='object')

In [6]:
college_df.isnull().sum()

UNITID               0
INSTNM               0
STABBR               0
REGION               0
LOCALE               0
CONTROL              0
ADM_RATE           137
SAT_AVG            572
ACTCMMID           605
UGDS                 0
COSTT4_A            14
TUITIONFEE_IN        0
TUITIONFEE_OUT       0
PCTPELL              0
PCTFLOAN             0
RET_FT4             11
C150_4               9
GRAD_DEBT_MDN        0
MD_EARN_WNE_4YR     20
MD_EARN_WNE_P10      0
dtype: int64

In [9]:
college_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UNITID           1520 non-null   int64
 1   INSTNM           1520 non-null   object
 2   STABBR           1520 non-null   object
 3   REGION           1520 non-null   int64
 4   LOCALE           1520 non-null   float64
 5   CONTROL          1520 non-null   int64
 6   ADM_RATE         1383 non-null   float64
 7   SAT_AVG          948 non-null    float64
 8   ACTCMMID         915 non-null    float64
 9   UGDS             1520 non-null   float64
 10  COSTT4_A         1506 non-null   float64
 11  TUITIONFEE_IN    1520 non-null   float64
 12  TUITIONFEE_OUT   1520 non-null   float64
 13  PCTPELL          1520 non-null   float64
 14  PCTFLOAN         1520 non-null   float64
 15  RET_FT4          1509 non-null   float64
 16  C150_4           1511 non-null   float64
 17  GRAD_DEBT_MDN    1520 non-null   float64
 18  MD_EARN_WNE_4YR  1500 non-null   float64
 19  MD_EARN_WNE_P10  1520 non-null   float64
dtypes: float64(15), int64(3), object(2)
memory usage: 237.6+ KB

In [11]:
college_df.describe()

,UNITID,REGION,LOCALE,CONTROL,ADM_RATE,SAT_AVG,ACTCMMID,UGDS,COSTT4_A,TUITIONFEE_IN,TUITIONFEE_OUT,PCTPELL,PCTFLOAN,RET_FT4,C150_4,GRAD_DEBT_MDN,MD_EARN_WNE_4YR,MD_EARN_WNE_P10
count,1520.000000,1520.000000,1520.000000,1520.000000,1383.000000,948.000000,915.000000,1520.000000,1506.000000,1520.000000,1520.000000,1520.000000,1520.000000,1509.000000,1511.000000,1520.000000,1500.000000,1520.000000
mean,191617.030921,4.223026,20.309868,1.692105,0.712014,1187.740506,24.496175,5497.743421,43288.204515,28527.276974,32679.221711,0.351309,0.463450,0.751822,0.565682,22710.688816,61865.379333,55883.546711
std,64430.926875,2.122235,10.008589,0.525771,0.221358,148.779356,4.195279,10122.501590,19785.297689,18591.580176,16052.523692,0.157381,0.185923,0.135981,0.182357,4837.049282,15825.604624,15631.799712
min,100654.000000,0.000000,11.000000,1.000000,0.036100,850.000000,14.000000,23.000000,9168.000000,895.000000,895.000000,0.000000,0.000000,0.000000,0.000000,3591.000000,22917.000000,19474.000000
25%,153381.750000,2.000000,12.000000,1.000000,0.606050,1087.000000,21.000000,995.750000,26077.750000,11134.000000,19768.250000,0.235650,0.331925,0.686600,0.443850,20290.000000,52293.250000,46000.250000
50%,185417.000000,4.000000,21.000000,2.000000,0.760600,1167.000000,24.000000,2093.000000,40404.000000,25879.000000,30636.000000,0.327950,0.458500,0.762800,0.561200,23250.000000,59521.000000,53781.000000
75%,217083.250000,5.000000,31.000000,2.000000,0.878500,1275.250000,27.000000,5671.000000,56597.250000,41477.250000,42333.000000,0.433625,0.604725,0.839600,0.687450,26000.000000,68695.250000,62496.250000
max,498571.000000,9.000000,43.000000,3.000000,1.000000,1560.000000,35.000000,163164.000000,93512.000000,72097.000000,72097.000000,0.992800,1.000000,1.000000,1.000000,43021.000000,161961.000000,143372.000000

In [14]:
college_df['STABBR'].value_counts()

STABBR
NY    113
CA    100
PA     89
TX     75
MA     65
OH     60
IL     57
NC     53
GA     45
MO     45
FL     43
IN     41
MI     40
VA     39
TN     39
MN     36
WI     33
SC     33
IA     29
PR     29
NJ     27
KY     26
AL     25
MD     25
KS     24
OK     23
LA     22
CO     21
WA     21
AR     20
CT     20
OR     19
NE     19
ME     17
WV     16
MS     15
NH     11
AZ     11
SD     11
MT     10
RI      9
ND      9
DC      9
VT      9
NM      7
ID      6
HI      6
UT      6
DE      4
NV      3
AK      2
WY      1
GU      1
VI      1
Name: count, dtype: int64

Data Cleaning

In [19]:
college_df = college_df.rename(columns={'UNITID': 'Unique Institutional ID', 'INSTNM':'Institution Name', 'STABBR':'State', 'REGION':'Region', 'LOCALE':'Campus Urbanization Type', 'CONTROL':'Institutional Control', 'ADM_RATE':'Admission Rate',
       'SAT_AVG':'Avearge SAT Score', 'ACTCMMID': 'Average ACT Midpoint', 'UGDS':'Undergarduate Enrollment', 'COSTT4_A':'Avearge Cost of Attendance', 'TUITIONFEE_IN':'Instate Tution',
       'TUITIONFEE_OUT':'Out of State Tution', 'PCTPELL':'Pell Grant Percentage', 'PCTFLOAN':'Federal Student Loan Percentage', 'RET_FT4':'Full-Time Retention Rate', 'C150_4':'Four-Year Institution Graduation Rate',
       'GRAD_DEBT_MDN':'Median Graduate Debt', 'MD_EARN_WNE_4YR':'Median Earnings 4 Years Post-Graduation', 'MD_EARN_WNE_P10':'Median Earnings 10 Years Post-Graduation'})
college_df.head()

,Unique Institutional ID,Institution Name,State,Region,Campus Urbanization Type,Institutional Control,Admission Rate,Avearge SAT Score,Average ACT Midpoint,Undergarduate Enrollment,Avearge Cost of Attendance,Instate Tution,Out of State Tution,Pell Grant Percentage,Federal Student Loan Percentage,Full-Time Retention Rate,Four-Year Institution Graduation Rate,Median Graduate Debt,Median Earnings 4 Years Post-Graduation,Median Earnings 10 Years Post-Graduation
0,100654,Alabama A & M University,AL,5,12.0,1,0.5795,938.0,18.0,6124.0,27153.0,10024.0,18634.0,0.6298,0.7454,0.6989,0.2403,31000.0,54018.0,40628.0
1,100663,University of Alabama at Birmingham,AL,5,12.0,1,0.8818,1258.0,27.0,11635.0,28145.0,9098.0,22562.0,0.3402,0.4027,0.8009,0.6423,22300.0,64969.0,54501.0
2,100690,Amridge University,AL,5,12.0,2,NaN,NaN,NaN,241.0,NaN,7590.0,7590.0,0.7655,0.8097,NaN,1.0000,32189.0,50075.0,37621.0
3,100706,University of Alabama in Huntsville,AL,5,12.0,1,0.6857,1319.0,28.0,6591.0,27392.0,12132.0,26408.0,0.2464,0.3255,0.8425,0.6429,20705.0,81045.0,61767.0
4,100724,Alabama State University,AL,5,12.0,1,0.9755,976.0,18.0,3477.0,23586.0,11248.0,19576.0,0.7134,0.7420,0.6975,0.3034,31000.0,45998.0,34502.0