<a href="https://colab.research.google.com/github/mjwillis717-coder/dsrp/blob/main/DSRP_Education.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import csv
import pandas as pd

In [61]:
college_csv = '/College_Scorecard_Cleaned (1).csv'
college_df = pd.read_csv(college_csv)
college_df.head()

,UNITID,INSTNM,STABBR,REGION,LOCALE,CONTROL,ADM_RATE,SAT_AVG,ACTCMMID,UGDS,COSTT4_A,TUITIONFEE_IN,TUITIONFEE_OUT,PCTPELL,PCTFLOAN,RET_FT4,C150_4,GRAD_DEBT_MDN,MD_EARN_WNE_4YR,MD_EARN_WNE_P10
0,100654,Alabama A & M University,AL,5,12.0,1,0.5795,938.0,18.0,6124.0,27153.0,10024.0,18634.0,0.6298,0.7454,0.6989,0.2403,31000.0,54018.0,40628.0
1,100663,University of Alabama at Birmingham,AL,5,12.0,1,0.8818,1258.0,27.0,11635.0,28145.0,9098.0,22562.0,0.3402,0.4027,0.8009,0.6423,22300.0,64969.0,54501.0
2,100690,Amridge University,AL,5,12.0,2,NaN,NaN,NaN,241.0,NaN,7590.0,7590.0,0.7655,0.8097,NaN,1.0000,32189.0,50075.0,37621.0
3,100706,University of Alabama in Huntsville,AL,5,12.0,1,0.6857,1319.0,28.0,6591.0,27392.0,12132.0,26408.0,0.2464,0.3255,0.8425,0.6429,20705.0,81045.0,61767.0
4,100724,Alabama State University,AL,5,12.0,1,0.9755,976.0,18.0,3477.0,23586.0,11248.0,19576.0,0.7134,0.7420,0.6975,0.3034,31000.0,45998.0,34502.0

In [62]:
college_df.columns

Index(['UNITID', 'INSTNM', 'STABBR', 'REGION', 'LOCALE', 'CONTROL', 'ADM_RATE',
       'SAT_AVG', 'ACTCMMID', 'UGDS', 'COSTT4_A', 'TUITIONFEE_IN',
       'TUITIONFEE_OUT', 'PCTPELL', 'PCTFLOAN', 'RET_FT4', 'C150_4',
       'GRAD_DEBT_MDN', 'MD_EARN_WNE_4YR', 'MD_EARN_WNE_P10'],
      dtype='object')

In [63]:
college_df.isnull().sum()

UNITID               0
INSTNM               0
STABBR               0
REGION               0
LOCALE               0
CONTROL              0
ADM_RATE           137
SAT_AVG            572
ACTCMMID           605
UGDS                 0
COSTT4_A            14
TUITIONFEE_IN        0
TUITIONFEE_OUT       0
PCTPELL              0
PCTFLOAN             0
RET_FT4             11
C150_4               9
GRAD_DEBT_MDN        0
MD_EARN_WNE_4YR     20
MD_EARN_WNE_P10      0
dtype: int64

In [64]:
college_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UNITID           1520 non-null   int64
 1   INSTNM           1520 non-null   object
 2   STABBR           1520 non-null   object
 3   REGION           1520 non-null   int64
 4   LOCALE           1520 non-null   float64
 5   CONTROL          1520 non-null   int64
 6   ADM_RATE         1383 non-null   float64
 7   SAT_AVG          948 non-null    float64
 8   ACTCMMID         915 non-null    float64
 9   UGDS             1520 non-null   float64
 10  COSTT4_A         1506 non-null   float64
 11  TUITIONFEE_IN    1520 non-null   float64
 12  TUITIONFEE_OUT   1520 non-null   float64
 13  PCTPELL          1520 non-null   float64
 14  PCTFLOAN         1520 non-null   float64
 15  RET_FT4          1509 non-null   float64
 16  C150_4           1511 non-null   float64
 17  GRAD_DEBT_MDN    1520 non-null   float64
 18  MD_EARN_WNE_4YR  1500 non-null   float64
 19  MD_EARN_WNE_P10  1520 non-null   float64
dtypes: float64(15), int64(3), object(2)
memory usage: 237.6+ KB

In [65]:
college_df.describe()

,UNITID,REGION,LOCALE,CONTROL,ADM_RATE,SAT_AVG,ACTCMMID,UGDS,COSTT4_A,TUITIONFEE_IN,TUITIONFEE_OUT,PCTPELL,PCTFLOAN,RET_FT4,C150_4,GRAD_DEBT_MDN,MD_EARN_WNE_4YR,MD_EARN_WNE_P10
count,1520.000000,1520.000000,1520.000000,1520.000000,1383.000000,948.000000,915.000000,1520.000000,1506.000000,1520.000000,1520.000000,1520.000000,1520.000000,1509.000000,1511.000000,1520.000000,1500.000000,1520.000000
mean,191617.030921,4.223026,20.309868,1.692105,0.712014,1187.740506,24.496175,5497.743421,43288.204515,28527.276974,32679.221711,0.351309,0.463450,0.751822,0.565682,22710.688816,61865.379333,55883.546711
std,64430.926875,2.122235,10.008589,0.525771,0.221358,148.779356,4.195279,10122.501590,19785.297689,18591.580176,16052.523692,0.157381,0.185923,0.135981,0.182357,4837.049282,15825.604624,15631.799712
min,100654.000000,0.000000,11.000000,1.000000,0.036100,850.000000,14.000000,23.000000,9168.000000,895.000000,895.000000,0.000000,0.000000,0.000000,0.000000,3591.000000,22917.000000,19474.000000
25%,153381.750000,2.000000,12.000000,1.000000,0.606050,1087.000000,21.000000,995.750000,26077.750000,11134.000000,19768.250000,0.235650,0.331925,0.686600,0.443850,20290.000000,52293.250000,46000.250000
50%,185417.000000,4.000000,21.000000,2.000000,0.760600,1167.000000,24.000000,2093.000000,40404.000000,25879.000000,30636.000000,0.327950,0.458500,0.762800,0.561200,23250.000000,59521.000000,53781.000000
75%,217083.250000,5.000000,31.000000,2.000000,0.878500,1275.250000,27.000000,5671.000000,56597.250000,41477.250000,42333.000000,0.433625,0.604725,0.839600,0.687450,26000.000000,68695.250000,62496.250000
max,498571.000000,9.000000,43.000000,3.000000,1.000000,1560.000000,35.000000,163164.000000,93512.000000,72097.000000,72097.000000,0.992800,1.000000,1.000000,1.000000,43021.000000,161961.000000,143372.000000

In [66]:
college_df['STABBR'].value_counts()

STABBR
NY    113
CA    100
PA     89
TX     75
MA     65
OH     60
IL     57
NC     53
GA     45
MO     45
FL     43
IN     41
MI     40
VA     39
TN     39
MN     36
WI     33
SC     33
IA     29
PR     29
NJ     27
KY     26
AL     25
MD     25
KS     24
OK     23
LA     22
CO     21
WA     21
AR     20
CT     20
OR     19
NE     19
ME     17
WV     16
MS     15
NH     11
AZ     11
SD     11
MT     10
RI      9
ND      9
DC      9
VT      9
NM      7
ID      6
HI      6
UT      6
DE      4
NV      3
AK      2
WY      1
GU      1
VI      1
Name: count, dtype: int64

Data Cleaning

In [67]:
college_df = college_df.rename(columns={'UNITID': 'Unique Institutional ID', 'INSTNM':'Institution Name', 'STABBR':'State', 'REGION':'Region', 'LOCALE':'Campus Urbanization Type', 'CONTROL':'Institutional Control', 'ADM_RATE':'Admission Rate',
       'SAT_AVG':'Avearge SAT Score', 'ACTCMMID': 'Average ACT Midpoint', 'UGDS':'Undergarduate Enrollment', 'COSTT4_A':'Avearge Cost of Attendance', 'TUITIONFEE_IN':'Instate Tution',
       'TUITIONFEE_OUT':'Out of State Tution', 'PCTPELL':'Pell Grant Percentage', 'PCTFLOAN':'Federal Student Loan Percentage', 'RET_FT4':'Full-Time Retention Rate', 'C150_4':'Four-Year Institution Graduation Rate',
       'GRAD_DEBT_MDN':'Median Graduate Debt', 'MD_EARN_WNE_4YR':'Median Earnings 4 Years Post-Graduation', 'MD_EARN_WNE_P10':'Median Earnings 10 Years Post-Graduation'})
college_df.head()

,Unique Institutional ID,Institution Name,State,Region,Campus Urbanization Type,Institutional Control,Admission Rate,Avearge SAT Score,Average ACT Midpoint,Undergarduate Enrollment,Avearge Cost of Attendance,Instate Tution,Out of State Tution,Pell Grant Percentage,Federal Student Loan Percentage,Full-Time Retention Rate,Four-Year Institution Graduation Rate,Median Graduate Debt,Median Earnings 4 Years Post-Graduation,Median Earnings 10 Years Post-Graduation
0,100654,Alabama A & M University,AL,5,12.0,1,0.5795,938.0,18.0,6124.0,27153.0,10024.0,18634.0,0.6298,0.7454,0.6989,0.2403,31000.0,54018.0,40628.0
1,100663,University of Alabama at Birmingham,AL,5,12.0,1,0.8818,1258.0,27.0,11635.0,28145.0,9098.0,22562.0,0.3402,0.4027,0.8009,0.6423,22300.0,64969.0,54501.0
2,100690,Amridge University,AL,5,12.0,2,NaN,NaN,NaN,241.0,NaN,7590.0,7590.0,0.7655,0.8097,NaN,1.0000,32189.0,50075.0,37621.0
3,100706,University of Alabama in Huntsville,AL,5,12.0,1,0.6857,1319.0,28.0,6591.0,27392.0,12132.0,26408.0,0.2464,0.3255,0.8425,0.6429,20705.0,81045.0,61767.0
4,100724,Alabama State University,AL,5,12.0,1,0.9755,976.0,18.0,3477.0,23586.0,11248.0,19576.0,0.7134,0.7420,0.6975,0.3034,31000.0,45998.0,34502.0

In [68]:
average = college_df['Avearge Cost of Attendance'].mean()
college_df['Avearge Cost of Attendance'] = college_df['Avearge Cost of Attendance'].fillna(value=average)

In [69]:
average = college_df['Full-Time Retention Rate'].mean()
college_df['Full-Time Retention Rate'] = college_df['Full-Time Retention Rate'].fillna(value=average)

In [70]:
average = college_df['Median Earnings 4 Years Post-Graduation'].mean()
college_df['Median Earnings 4 Years Post-Graduation'] = college_df['Median Earnings 4 Years Post-Graduation'].fillna(value=average)

In [71]:
average = college_df['Admission Rate'].mean()
college_df['Admission Rate'] = college_df['Admission Rate'].fillna(value=average)

In [72]:
average = college_df['Four-Year Institution Graduation Rate'].mean()
college_df['Four-Year Institution Graduation Rate'] = college_df['Four-Year Institution Graduation Rate'].fillna(value=average)

In [73]:
college_df.head()

,Unique Institutional ID,Institution Name,State,Region,Campus Urbanization Type,Institutional Control,Admission Rate,Avearge SAT Score,Average ACT Midpoint,Undergarduate Enrollment,Avearge Cost of Attendance,Instate Tution,Out of State Tution,Pell Grant Percentage,Federal Student Loan Percentage,Full-Time Retention Rate,Four-Year Institution Graduation Rate,Median Graduate Debt,Median Earnings 4 Years Post-Graduation,Median Earnings 10 Years Post-Graduation
0,100654,Alabama A & M University,AL,5,12.0,1,0.579500,938.0,18.0,6124.0,27153.000000,10024.0,18634.0,0.6298,0.7454,0.698900,0.2403,31000.0,54018.0,40628.0
1,100663,University of Alabama at Birmingham,AL,5,12.0,1,0.881800,1258.0,27.0,11635.0,28145.000000,9098.0,22562.0,0.3402,0.4027,0.800900,0.6423,22300.0,64969.0,54501.0
2,100690,Amridge University,AL,5,12.0,2,0.712014,NaN,NaN,241.0,43288.204515,7590.0,7590.0,0.7655,0.8097,0.751822,1.0000,32189.0,50075.0,37621.0
3,100706,University of Alabama in Huntsville,AL,5,12.0,1,0.685700,1319.0,28.0,6591.0,27392.000000,12132.0,26408.0,0.2464,0.3255,0.842500,0.6429,20705.0,81045.0,61767.0
4,100724,Alabama State University,AL,5,12.0,1,0.975500,976.0,18.0,3477.0,23586.000000,11248.0,19576.0,0.7134,0.7420,0.697500,0.3034,31000.0,45998.0,34502.0

In [74]:
college_df['Avearge SAT Score'] = college_df['Avearge SAT Score'].fillna('Test Optional')

In [75]:
college_df['Average ACT Midpoint'] = college_df['Average ACT Midpoint'].fillna('Test Optional')

In [76]:
college_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 20 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Unique Institutional ID                   1520 non-null   int64
 1   Institution Name                          1520 non-null   object
 2   State                                     1520 non-null   object
 3   Region                                    1520 non-null   int64
 4   Campus Urbanization Type                  1520 non-null   float64
 5   Institutional Control                     1520 non-null   int64
 6   Admission Rate                            1520 non-null   float64
 7   Avearge SAT Score                         1520 non-null   object
 8   Average ACT Midpoint                      1520 non-null   object
 9   Undergarduate Enrollment                  1520 non-null   float64
 10  Avearge Cost of Attendance                1520 non-null   float64
 11  Instate Tution                            1520 non-null   float64
 12  Out of State Tution                       1520 non-null   float64
 13  Pell Grant Percentage                     1520 non-null   float64
 14  Federal Student Loan Percentage           1520 non-null   float64
 15  Full-Time Retention Rate                  1520 non-null   float64
 16  Four-Year Institution Graduation Rate     1520 non-null   float64
 17  Median Graduate Debt                      1520 non-null   float64
 18  Median Earnings 4 Years Post-Graduation   1520 non-null   float64
 19  Median Earnings 10 Years Post-Graduation  1520 non-null   float64
dtypes: float64(13), int64(3), object(4)
memory usage: 237.6+ KB

In [77]:
college_df['Admission Rate (median)'] = [0.5795, 0.8818, 0.7606, 0.6857, 0.9755, 0.7665, 0.9157, 0.4592, 0.7307, 0.6949, 0.7769, 0.4265, 0.7606, 0.7789, 0.5385, 0.8731, 0.4522, 0.8236, 0.7096, 0.7657, 0.6225, 0.8542, 0.9604, 0.4868, 0.7606, 0.7606, 0.8989, 0.8614, 0.7891, 0.8961, 0.9451, 0.7062, 0.5878, 0.7606, 0.6276, 0.743, 0.4118, 0.8226, 0.8949, 0.6346, 0.7606, 0.7052, 0.7606, 0.5565, 0.7614, 0.6752, 0.5951, 0.7606, 0.8342, 0.7533, 0.7606, 0.7454, 0.8843, 0.7435, 0.8488, 0.911, 0.7567, 0.3132, 0.9385, 0.9814, 0.9374, 0.7517, 0.9272, 0.933, 0.9526, 0.9052, 0.9739, 0.4627, 0.9125, 0.9345, 0.9399, 0.1098, 0.4183, 0.2857, 0.0897, 0.7639, 0.2671, 0.3297, 0.6579, 0.3234, 0.9501, 0.6543, 0.3874, 0.6599, 0.3081, 0.0959, 0.5118, 0.7606, 1.0, 0.835, 0.6407, 0.1266, 0.982, 0.7606, 0.958, 0.7117, 0.9432, 0.915, 0.8402, 0.4508, 0.6847, 0.7313, 0.7606, 1.0, 0.4417, 0.8176, 0.3298, 0.3438, 0.473, 0.7132, 0.6286, 0.2516, 0.8368, 0.0709, 0.8271, 0.3619, 0.5238, 0.9644, 0.6171, 0.9333, 0.8461, 0.48, 0.3829, 0.8603, 0.8653, 0.9343, 0.6244, 0.0981, 0.8309, 0.7606, 0.7705, 0.8079, 0.8165, 0.7606, 0.7468, 0.9735, 0.7808, 0.7606, 0.1847, 0.6069, 0.8854, 0.7606, 0.7781, 0.773, 0.8203, 0.988, 1.0, 0.7606, 0.8585, 0.8646, 0.7606, 0.949, 0.9971, 0.5931, 0.8302, 0.7333, 0.7606, 0.3704, 0.5239, 0.8298, 0.3329, 0.9575, 0.9466, 0.6038, 0.7606, 0.7215, 0.6536, 0.7859, 0.9147, 0.2925, 0.1649, 0.8701, 0.0387, 0.4658, 0.706, 0.8451, 0.7606, 0.6196, 0.8278, 0.5806, 0.4709, 0.1291, 0.4134, 0.7606, 0.9952, 0.3599, 0.7724, 0.8824, 0.7347, 0.4011, 0.758, 0.6481, 0.2056, 0.6613, 0.8076, 0.6966, 0.7606, 0.577, 0.5466, 0.8526, 0.6442, 0.2422, 0.242, 0.7606, 0.5694, 0.9167, 0.189, 0.5324, 0.7321, 0.8199, 0.6965, 0.4754, 0.784, 0.4319, 0.9791, 0.716, 0.5298, 0.4034, 0.5328, 0.9189, 0.4281, 0.694, 0.5824, 0.7572, 0.6215, 0.7606, 0.6422, 0.64, 0.8778, 0.9649, 0.9813, 0.6845, 0.9912, 0.8651, 0.7606, 0.7606, 0.74, 0.1065, 0.6587, 0.1407, 0.7517, 0.7823, 0.8789, 0.5544, 0.377, 0.6209, 0.9303, 0.6889, 0.4396, 0.8845, 0.9328, 0.6154, 0.8298, 0.7606, 0.9646, 0.383, 0.6596, 0.7826, 0.7229, 0.591, 0.5161, 0.6264, 0.9143, 0.6063, 0.866, 0.8587, 0.9534, 0.8721, 0.7606, 0.7553, 0.491, 0.8769, 0.6474, 0.7747, 0.6268, 0.8085, 0.6319, 0.7676, 0.4326, 0.0448, 0.8946, 0.9279, 0.7589, 0.7606, 0.6535, 0.7364, 0.8499, 0.4827, 0.975, 0.5714, 0.7735, 0.9523, 0.4237, 0.3931, 0.7819, 0.5493, 0.8815, 0.4759, 0.7079, 0.5681, 0.7129, 0.816, 0.7172, 0.3889, 0.6668, 0.9093, 0.8269, 0.9505, 0.7733, 0.6851, 0.6979, 0.0769, 0.746, 0.5586, 0.5093, 0.9291, 0.9716, 0.9032, 0.6529, 0.843, 0.8588, 0.7606, 0.8688, 0.975, 0.8492, 1.0, 0.8947, 0.7118, 0.874, 0.7934, 0.855, 0.9766, 0.8508, 0.7606, 0.5719, 0.7311, 0.776, 0.698, 0.8407, 0.8215, 0.837, 0.7518, 0.7564, 0.8389, 0.7637, 0.665, 0.7039, 0.8077, 0.8648, 0.8384, 0.7821, 0.7339, 0.8446, 0.6722, 0.7106, 0.9546, 0.8894, 0.7606, 0.1127, 0.8251, 0.7686, 0.9597, 0.7239, 0.7597, 0.7353, 0.8548, 0.8943, 0.633, 0.7606, 0.7761, 0.8617, 0.7183, 0.6404, 0.799, 0.6847, 0.6385, 0.8863, 0.6752, 0.8083, 0.9909, 0.1451, 0.8866, 0.8362, 0.9986, 0.7154, 0.957, 0.9971, 0.7104, 0.8252, 0.7606, 0.9274, 0.8036, 0.7733, 0.8622, 0.9646, 0.7698, 0.7584, 0.5188, 0.9419, 0.9812, 0.56, 0.935, 0.5271, 0.9771, 0.9026, 0.5098, 0.5522, 0.9348, 0.7398, 0.8169, 0.719, 1.0, 0.7676, 0.788, 0.8296, 0.8663, 0.7555, 0.4817, 0.6458, 0.7606, 0.9395, 0.7523, 0.634, 0.8611, 0.1934, 0.3524, 0.7974, 0.5436, 0.9881, 0.7761, 0.9106, 0.9608, 0.716, 0.9294, 0.6091, 0.7606, 0.7941, 0.9514, 0.7721, 0.8568, 0.6765, 0.7606, 0.9945, 0.9035, 0.8655, 0.6315, 0.9387, 0.5574, 0.4186, 0.4486, 0.9208, 0.7333, 0.5055, 0.7719, 0.864, 0.9305, 0.7827, 0.7431, 0.908, 0.8475, 0.9254, 0.7366, 0.987, 0.9931, 0.3512, 0.789, 0.8701, 0.1398, 0.6904, 0.7017, 0.1332, 0.0713, 0.0709, 0.7606, 0.9672, 0.9792, 0.9664, 0.5414, 0.9987, 0.9163, 0.7606, 0.8351, 0.7923, 0.963, 0.7606, 0.7874, 0.7241, 0.7435, 0.4618, 0.4583, 0.8918, 0.7771, 0.7777, 0.0644, 0.7549, 0.7606, 0.7243, 0.4479, 0.7679, 0.9641, 0.8223, 0.7381, 0.8216, 0.8747, 0.6863, 0.5524, 0.8197, 0.7891, 0.5689, 0.7793, 0.9957, 0.0901, 0.503, 0.8298, 0.1709, 0.852, 0.4505, 0.4353, 0.7606, 0.1643, 0.1111, 0.405, 0.8781, 0.7606, 0.3954, 0.8765, 0.7371, 0.7606, 0.5131, 0.7565, 0.7121, 0.7068, 0.8693, 0.8361, 0.6923, 0.7528, 0.0365, 0.7963, 0.1761, 0.8122, 0.9687, 0.8304, 0.5973, 0.8378, 0.8521, 0.7627, 0.0455, 0.947, 0.7002, 0.7606, 0.3603, 0.411, 0.8084, 0.8974, 0.0522, 0.8526, 0.6978, 0.9588, 0.6998, 0.21, 0.7189, 0.9064, 0.6628, 0.8233, 0.1149, 0.1405, 0.9121, 0.8348, 0.8141, 0.6773, 0.0825, 0.6016, 0.8799, 0.7253, 0.807, 0.5703, 0.8185, 0.8988, 0.8187, 0.7091, 0.8982, 0.6754, 0.9194, 0.9784, 0.7542, 0.7964, 0.9139, 0.7867, 0.9916, 0.7777, 0.8302, 0.7606, 0.7924, 0.7532, 0.7606, 0.559, 0.6339, 0.9765, 0.1564, 0.848, 0.9243, 0.5561, 0.7046, 0.8402, 0.6451, 0.8784, 0.8325, 0.691, 0.7207, 0.689, 0.5152, 0.8116, 0.846, 0.7606, 0.8198, 0.5598, 0.3897, 0.878, 0.2041, 0.6265, 0.7887, 0.8717, 0.6099, 0.8763, 0.2852, 0.8844, 0.9871, 0.7975, 0.8786, 0.4848, 0.8875, 0.7493, 0.5876, 0.9898, 0.9347, 0.7606, 0.9152, 0.948, 0.9062, 0.9278, 0.4832, 0.2278, 0.9296, 0.8536, 0.9185, 0.6218, 0.7549, 0.4533, 0.4975, 0.8895, 1.0, 0.9315, 0.4312, 0.9658, 0.9031, 0.9238, 0.2911, 0.7764, 0.4867, 0.9912, 0.5985, 0.6029, 0.878, 0.7606, 1.0, 0.7174, 0.7606, 0.5687, 0.638, 0.6923, 0.7606, 0.6918, 0.991, 0.5758, 0.7161, 0.7263, 0.7606, 0.5476, 0.7606, 0.5684, 0.6429, 0.9508, 0.964, 0.686, 0.9703, 0.6918, 0.7606, 0.7847, 0.7218, 0.7255, 0.6267, 0.8377, 0.8609, 0.9361, 0.7606, 1.0, 0.6959, 0.7504, 0.8984, 0.6839, 0.7722, 0.7352, 0.9053, 0.1206, 0.8623, 0.792, 0.3836, 0.7096, 0.7093, 0.7606, 0.5028, 0.9105, 0.8214, 0.9586, 0.7606, 0.6961, 0.7606, 0.9978, 0.7606, 0.7818, 0.6737, 0.7606, 0.8572, 0.7975, 0.9801, 0.7165, 0.8949, 0.7341, 0.6612, 0.8698, 0.7982, 0.8749, 0.7606, 0.4465, 1.0, 0.7606, 0.5188, 0.9617, 0.7371, 0.8008, 0.054, 0.9347, 0.9213, 0.9951, 0.8816, 0.9033, 0.8754, 0.8259, 0.7805, 0.7606, 0.7606, 0.7134, 0.8308, 0.6783, 0.9071, 0.7606, 0.7884, 0.7766, 0.9838, 0.759, 0.8902, 0.8789, 0.6507, 0.0462, 0.7064, 0.7864, 0.5815, 0.903, 0.7326, 0.7103, 0.4758, 0.8894, 0.7606, 0.6229, 0.9008, 0.9166, 0.7606, 0.4449, 0.9518, 0.8897, 0.7606, 0.7606, 0.6591, 0.5269, 0.7384, 0.5212, 0.0884, 0.7606, 0.7606, 0.7236, 0.7736, 0.1388, 0.9, 0.0399, 0.2071, 0.0876, 0.4752, 0.5836, 0.9234, 0.6002, 0.6849, 0.538, 0.5711, 0.5658, 0.8605, 0.8029, 0.6435, 0.641, 0.8137, 0.6826, 0.633, 0.7696, 0.5382, 0.5931, 0.1362, 0.696, 0.972, 0.6399, 0.6808, 0.8866, 0.8694, 0.6901, 0.0915, 0.6808, 0.959, 0.8298, 0.8616, 0.7894, 0.4078, 0.8734, 0.5651, 0.8261, 0.8584, 0.8174, 0.8888, 0.8511, 0.7472, 0.6347, 0.0923, 0.8737, 0.8102, 0.7592, 0.7653, 0.7325, 0.6347, 0.7063, 0.6693, 0.4008, 0.5326, 0.8165, 0.7606, 0.5434, 0.9305, 0.6173, 0.6902, 0.2105, 0.7205, 0.664, 0.8343, 0.9215, 0.8901, 0.8402, 0.6329, 0.691, 0.3861, 0.7418, 0.4904, 0.6328, 0.8135, 0.7068, 0.7295, 0.5979, 0.777, 0.6645, 0.6161, 0.696, 0.8055, 0.777, 0.7405, 0.8363, 0.7841, 0.7606, 0.7241, 0.4592, 0.6083, 0.4392, 0.3424, 0.9195, 0.1857, 0.8659, 0.9264, 0.88, 0.9442, 0.5562, 0.9014, 0.942, 0.7465, 0.5066, 0.4216, 0.8718, 0.7521, 0.6879, 0.1337, 0.0571, 0.8921, 0.6422, 0.6635, 0.8215, 0.7721, 0.7014, 0.8, 0.7531, 0.4521, 0.7678, 0.8459, 0.5925, 0.679, 0.7418, 0.7514, 0.692, 0.7575, 0.499, 0.9192, 0.1534, 0.796, 0.8851, 0.8696, 0.2997, 0.4174, 0.8023, 0.6424, 0.9425, 0.9326, 0.9603, 0.6208, 0.6216, 0.338, 0.7667, 0.8016, 0.2167, 0.7134, 0.9113, 0.7826, 0.8183, 0.3702, 0.8808, 0.753, 0.7606, 0.6462, 0.769, 0.9496, 0.2575, 0.9907, 0.5967, 0.3449, 0.764, 0.4588, 0.757, 0.6723, 0.8096, 0.7022, 0.3654, 0.6529, 0.9861, 0.5894, 0.8529, 0.3797, 0.6135, 0.4731, 0.913, 0.6766, 0.6545, 0.4755, 0.1739, 0.8337, 0.7606, 0.8579, 0.9353, 0.809, 0.8634, 0.3103, 0.7654, 0.7036, 0.7413, 0.7586, 0.7931, 0.9322, 0.754, 0.8429, 0.782, 0.8415, 0.5912, 0.8184, 0.3418, 0.9423, 0.744, 0.6057, 0.8499, 0.556, 0.8453, 0.7606, 0.5836, 0.8005, 0.9202, 0.7493, 0.7074, 0.405, 0.924, 0.7235, 0.5953, 0.9633, 0.8641, 0.8445, 0.6617, 0.7606, 0.7606, 0.7812, 0.5815, 0.5786, 0.7606, 0.9959, 0.6545, 0.9654, 0.7606, 0.7504, 0.4941, 0.7702, 0.766, 0.989, 0.7606, 0.6582, 0.7643, 0.7606, 0.7606, 0.6151, 0.9831, 0.8, 0.9351, 0.7849, 0.8517, 0.6728, 0.9502, 0.773, 0.883, 0.7485, 0.8956, 0.9087, 0.8917, 0.2461, 0.8862, 0.7114, 0.939, 0.7709, 0.981, 0.8294, 0.7633, 0.5457, 0.7709, 0.5806, 0.8022, 0.2943, 0.2893, 0.8695, 0.1166, 0.8407, 0.1846, 0.6196, 0.7446, 0.7606, 0.9321, 0.4209, 0.7944, 0.8356, 0.9205, 0.9077, 0.7787, 0.2819, 0.7416, 0.7606, 0.389, 0.8963, 0.1237, 0.7104, 0.8576, 0.9077, 0.7891, 0.848, 0.9311, 0.9075, 0.7576, 0.9659, 0.3145, 0.5589, 0.8377, 0.2593, 0.6572, 0.7407, 0.6058, 0.8102, 0.7897, 0.8619, 0.7093, 0.5646, 0.5417, 0.8205, 0.7199, 0.8128, 0.6056, 0.7606, 0.7606, 0.9924, 0.054, 0.8817, 0.5808, 0.9691, 0.8989, 0.7634, 0.7682, 0.8883, 0.6173, 0.8123, 0.7953, 0.865, 0.7147, 0.8143, 0.0746, 0.8041, 0.7155, 0.8097, 0.9177, 0.612, 0.2698, 0.8064, 0.8982, 0.784, 0.9256, 0.7093, 0.9064, 0.9211, 0.7374, 0.0539, 0.6546, 0.8841, 0.5089, 0.9182, 0.7216, 0.1866, 0.8771, 0.6817, 0.7606, 0.7254, 0.5471, 0.9646, 0.957, 0.7606, 0.9953, 0.6003, 0.2272, 0.6493, 0.3834, 0.7606, 0.9396, 0.9447, 0.9393, 0.6774, 0.6274, 0.8639, 0.4295, 0.8131, 0.9726, 0.7606, 0.8979, 0.6667, 0.6837, 0.7854, 0.725, 0.6015, 0.7527, 0.8262, 0.6726, 0.7606, 0.7925, 0.5194, 0.6775, 0.9633, 0.8805, 0.7338, 0.4257, 0.7606, 0.93, 0.7987, 0.9834, 0.8289, 0.9878, 0.9641, 0.8202, 0.9528, 0.6023, 0.7606, 0.9045, 0.867, 0.6733, 0.6773, 0.8619, 0.3742, 0.7606, 0.5968, 0.6511, 0.9972, 0.7606, 0.9923, 0.7052, 0.6259, 0.8671, 0.6092, 0.7203, 0.6909, 0.5035, 0.569, 0.655, 0.6885, 0.8109, 0.416, 0.882, 0.7011, 0.7613, 0.6944, 0.7217, 0.6041, 0.0586, 0.6603, 0.8301, 0.7606, 0.4765, 0.5128, 0.9125, 0.8858, 0.8884, 0.218, 0.5344, 0.5776, 0.6354, 0.9224, 0.9, 0.8444, 0.9052, 0.8996, 0.959, 0.7392, 0.6737, 0.3909, 0.9814, 0.7606, 0.8641, 0.4437, 0.3801, 0.731, 0.9576, 0.5704, 0.9352, 0.7606, 0.7223, 0.7606, 0.9419, 0.4028, 0.7931, 0.08, 0.8142, 0.8992, 0.9026, 0.882, 0.9776, 0.6335, 0.8902, 0.4305, 0.9399, 0.8932, 0.7836, 0.9871, 0.8955, 0.9092, 0.5743, 0.799, 0.2664, 0.6513, 0.9992, 0.9402, 0.4449, 0.7606, 0.9571, 0.9489, 0.8679, 0.9691, 0.7265, 0.6916, 0.9612, 0.2592, 0.5596, 0.9868, 0.7606, 0.6778, 0.4696, 0.7606, 0.8598, 0.6657, 0.4453, 0.8292, 0.1075, 0.7444, 0.8451, 0.6667, 0.8167, 0.653, 0.5659, 0.5931, 0.9172, 0.3407, 0.3812, 0.8604, 0.8365, 1.0, 0.8898, 0.8748, 0.4092, 0.6225, 0.6795, 0.7152, 0.9898, 0.9022, 0.4301, 0.7606, 0.7978, 0.9316, 0.8777, 0.9036, 0.8953, 0.8661, 0.9371, 0.222, 0.8306, 0.7695, 0.9642, 0.7554, 0.2854, 0.5478, 0.9262, 0.1681, 0.7125, 0.8863, 0.9799, 0.7287, 0.1397, 0.9062, 0.6221, 0.9075, 0.9637, 0.8169, 0.7606, 0.832, 0.7802, 0.7225, 0.898, 0.834, 0.7692, 0.7606, 0.8664, 0.3915, 0.9325, 0.3815, 0.8978, 0.7778, 0.5879, 0.9723, 0.6152, 0.9256, 0.9433, 0.9862, 0.9573, 0.7606, 0.9678, 0.9596, 0.9727, 0.9334, 0.89, 0.6316, 0.8574, 0.9718, 0.6304, 0.6684, 0.8706, 0.782, 0.7573, 0.8628, 0.6394, 0.719, 0.7498, 0.8134, 0.6054, 0.5893, 0.6233, 0.7497, 0.7984, 0.8574, 0.7243, 0.8572, 0.8234, 0.8859, 0.755, 0.7816, 0.865, 0.7539, 0.8767, 0.9301, 0.452, 0.9068, 0.8938, 0.8172, 0.918, 0.9688, 0.7606, 1.0, 0.7606, 0.6594, 1.0, 0.9808, 0.7606, 0.7606, 0.7835, 0.4248, 0.4176, 0.382, 0.8595, 0.6972, 0.3373, 0.2654, 0.3962, 0.814, 0.5918, 0.3533, 0.5454, 0.53, 0.548, 0.5652, 0.5245, 0.5459, 0.7606, 0.5802, 0.7606, 0.7606, 0.9898, 0.0361, 0.4987, 0.7606, 0.9176, 0.4944, 0.7606, 0.732, 0.9806, 0.951, 0.4631, 0.6598, 0.7606, 0.4347, 0.7606, 0.8145, 0.7606, 0.4338, 0.7606, 0.974, 0.7606, 0.7606, 1.0, 0.6963, 0.5, 0.7606, 0.7606, 0.6344, 0.6064, 0.7606, 0.8682, 0.9481, 0.252, 0.7606, 0.7606, 0.7606, 0.6442, 0.7606, 0.7606, 0.9053, 0.4139, 0.7381, 0.8771, 0.8735, 0.955, 0.4068, 0.7606, 0.4182, 0.2803, 0.7606, 0.8264, 0.4634, 1.0, 0.7606, 0.928, 0.7606, 0.7606, 0.7963, 1.0, 0.984, 0.8641, 0.9968, 0.6794, 0.7606, 0.6919, 0.7229, 0.8095, 0.3954, 0.7236, 0.9309, 0.9433]

college_df['Average Cost of Attendance (median)'] = [27153.0, 28145.0, 40404.0, 27392.0, 23586.0, 33382.0, 21353.0, 34919.0, 37626.0, 40908.0, 24257.0, 22758.0, 21154.0, 41115.0, 27398.0, 23786.0, 40176.0, 57456.0, 25476.0, 39936.0, 26107.0, 25185.0, 23165.0, 43454.0, 24096.0, 22407.0, 30111.0, 29423.0, 32702.0, 29933.0, 48532.0, 54792.0, 22519.0, 23060.0, 44978.0, 27767.0, 21129.0, 25082.0, 25029.0, 30605.0, 27340.0, 39534.0, 27385.0, 55013.0, 44710.0, 47321.0, 38666.0, 28136.0, 33597.0, 24951.0, 48036.0, 75649.0, 56313.0, 62757.0, 54038.0, 79776.0, 68426.0, 32265.0, 19522.0, 19739.0, 17427.0, 23955.0, 26283.0, 23191.0, 20095.0, 18269.0, 22850.0, 22679.0, 18403.0, 20485.0, 22945.0, 45619.0, 41238.0, 38632.0, 38614.0, 38942.0, 38701.0, 41573.0, 41179.0, 77560.0, 29853.0, 83146.0, 39834.0, 58682.0, 31745.0, 86500.0, 35722.0, 31890.0, 55911.0, 71751.0, 44249.0, 90165.0, 25170.0, 20918.0, 35062.0, 62278.0, 57989.0, 51459.0, 54845.0, 83943.0, 72020.0, 66726.0, 33978.0, 62004.0, 84800.0, 75861.0, 51784.0, 40404.0, 49404.0, 71515.0, 93512.0, 86466.0, 60488.0, 85300.0, 76630.0, 27780.0, 78720.0, 26488.0, 80141.0, 53703.0, 26593.0, 82026.0, 87564.0, 54688.0, 77659.0, 24648.0, 52665.0, 90300.0, 43426.0, 35358.0, 71150.0, 63664.0, 58010.0, 24352.0, 24902.0, 24595.0, 37684.0, 54242.0, 86921.0, 40560.0, 31642.0, 23744.0, 78476.0, 27030.0, 24046.0, 24622.0, 53397.0, 40404.0, 29254.0, 54800.0, 37505.0, 23937.0, 25736.0, 59407.0, 52957.0, 24870.0, 23210.0, 84623.0, 39426.0, 31983.0, 76074.0, 64729.0, 55621.0, 66962.0, 28897.0, 72215.0, 69289.0, 59900.0, 29673.0, 87840.0, 89020.0, 24877.0, 88300.0, 27939.0, 30952.0, 26502.0, 19644.0, 76058.0, 75481.0, 40374.0, 83856.0, 88741.0, 54630.0, 40404.0, 33903.0, 23159.0, 50778.0, 29764.0, 67880.0, 23133.0, 68944.0, 64632.0, 23970.0, 21522.0, 45744.0, 34870.0, 38408.0, 62440.0, 21462.0, 35809.0, 60768.0, 25720.0, 22523.0, 47530.0, 63969.0, 31680.0, 86078.0, 20983.0, 56692.0, 53827.0, 80276.0, 76108.0, 45264.0, 22859.0, 51205.0, 72533.0, 49329.0, 51614.0, 26995.0, 24904.0, 41044.0, 50989.0, 19947.0, 13956.0, 63283.0, 19333.0, 43676.0, 56697.0, 46010.0, 38918.0, 21924.0, 17415.0, 21676.0, 57467.0, 12719.0, 36577.0, 37604.0, 83622.0, 19879.0, 28167.0, 20484.0, 30258.0, 24430.0, 28241.0, 27993.0, 49681.0, 41295.0, 58204.0, 51433.0, 60581.0, 46801.0, 46386.0, 63627.0, 17191.0, 35726.0, 23079.0, 37561.0, 39152.0, 20801.0, 40721.0, 21981.0, 48301.0, 45798.0, 21173.0, 26433.0, 50674.0, 18410.0, 28224.0, 21527.0, 23738.0, 50542.0, 21925.0, 55163.0, 75625.0, 63553.0, 40625.0, 37916.0, 54730.0, 29764.0, 90360.0, 51889.0, 45383.0, 63052.0, 32606.0, 26996.0, 54679.0, 39578.0, 24227.0, 45091.0, 35559.0, 27521.0, 46713.0, 33642.0, 70700.0, 48955.0, 68164.0, 34309.0, 43137.0, 68134.0, 70655.0, 47313.0, 67408.0, 48845.0, 46874.0, 57475.0, 57157.0, 34327.0, 24154.0, 57219.0, 44172.0, 28851.0, 91250.0, 26960.0, 51981.0, 50091.0, 49169.0, 35332.0, 43891.0, 46239.0, 43244.0, 25521.0, 40404.0, 28329.0, 28919.0, 35012.0, 16515.0, 44613.0, 28254.0, 59263.0, 51585.0, 26146.0, 43885.0, 65970.0, 32968.0, 74320.0, 67684.0, 57451.0, 54178.0, 48449.0, 41838.0, 58821.0, 50881.0, 42157.0, 22183.0, 23316.0, 52590.0, 45879.0, 24535.0, 11837.0, 17364.0, 28801.0, 13989.0, 16411.0, 16954.0, 49993.0, 56258.0, 44776.0, 23152.0, 83271.0, 42441.0, 77890.0, 47223.0, 49512.0, 66478.0, 53405.0, 51109.0, 58437.0, 65144.0, 51493.0, 54222.0, 37773.0, 55782.0, 67372.0, 66249.0, 51733.0, 64835.0, 53806.0, 32722.0, 48294.0, 48522.0, 83440.0, 24018.0, 28596.0, 50537.0, 65461.0, 27892.0, 34398.0, 52577.0, 55054.0, 37594.0, 22278.0, 49783.0, 51141.0, 61227.0, 34022.0, 39675.0, 64359.0, 42874.0, 50918.0, 52206.0, 53738.0, 52193.0, 33327.0, 21967.0, 19909.0, 42890.0, 50482.0, 26751.0, 46489.0, 27402.0, 47437.0, 34466.0, 50611.0, 57355.0, 51856.0, 48728.0, 58432.0, 47185.0, 50350.0, 21512.0, 21780.0, 31200.0, 47459.0, 61691.0, 60718.0, 44328.0, 42603.0, 67787.0, 25567.0, 23735.0, 56886.0, 21727.0, 46203.0, 34391.0, 40168.0, 40879.0, 32941.0, 48805.0, 21961.0, 23485.0, 19725.0, 33420.0, 45530.0, 49452.0, 60993.0, 44322.0, 24188.0, 60620.0, 39202.0, 25367.0, 15550.0, 34705.0, 19461.0, 33791.0, 24280.0, 64157.0, 22810.0, 23431.0, 23481.0, 24932.0, 25431.0, 27541.0, 28490.0, 23604.0, 26341.0, 23905.0, 24884.0, 87004.0, 40434.0, 58266.0, 83532.0, 85100.0, 85420.0, 19052.0, 25822.0, 18703.0, 27328.0, 31046.0, 19113.0, 63245.0, 60128.0, 59782.0, 23717.0, 47198.0, 21931.0, 26406.0, 25220.0, 42471.0, 34309.0, 23748.0, 27056.0, 70544.0, 61219.0, 85947.0, 74055.0, 25400.0, 28576.0, 29299.0, 76860.0, 25941.0, 25413.0, 63731.0, 59320.0, 28310.0, 31865.0, 55540.0, 28535.0, 58394.0, 73314.0, 65294.0, 59270.0, 87640.0, 61888.0, 65551.0, 80192.0, 47308.0, 79548.0, 72700.0, 40343.0, 89493.0, 86285.0, 86448.0, 26160.0, 34072.0, 68432.0, 64020.0, 64889.0, 42179.0, 80399.0, 65252.0, 59328.0, 53921.0, 25555.0, 27413.0, 42446.0, 74195.0, 85540.0, 41282.0, 80334.0, 42434.0, 51538.0, 30786.0, 34549.0, 30544.0, 65022.0, 34239.0, 82730.0, 31367.0, 70038.0, 58616.0, 84926.0, 81277.0, 58310.0, 26026.0, 84641.0, 54027.0, 65546.0, 28291.0, 63460.0, 86030.0, 60729.0, 33485.0, 72714.0, 65281.0, 88300.0, 86290.0, 61096.0, 60262.0, 27649.0, 79311.0, 84860.0, 78679.0, 22874.0, 56003.0, 69986.0, 63650.0, 45218.0, 51652.0, 24526.0, 54222.0, 30681.0, 39718.0, 66014.0, 37319.0, 42211.0, 29640.0, 27048.0, 61250.0, 26166.0, 42043.0, 28367.0, 30311.0, 55646.0, 74208.0, 27154.0, 58166.0, 41038.0, 41787.0, 34654.0, 32198.0, 34152.0, 24040.0, 20915.0, 27841.0, 48780.0, 25182.0, 47069.0, 38366.0, 24936.0, 44449.0, 44703.0, 27350.0, 29237.0, 33874.0, 62303.0, 22744.0, 41013.0, 58569.0, 84893.0, 45942.0, 37239.0, 29250.0, 67613.0, 58110.0, 82991.0, 23995.0, 25172.0, 30061.0, 26068.0, 59972.0, 27680.0, 27039.0, 25197.0, 44475.0, 51325.0, 33958.0, 68453.0, 21116.0, 68521.0, 57380.0, 71843.0, 46598.0, 55103.0, 66116.0, 60476.0, 24757.0, 23683.0, 23751.0, 39793.0, 33197.0, 22445.0, 32415.0, 60061.0, 28660.0, 22225.0, 21154.0, 41214.0, 29267.0, 23107.0, 26566.0, 24239.0, 29651.0, 50096.0, 28448.0, 40404.0, 23938.0, 24748.0, 43635.0, 22947.0, 40764.0, 37207.0, 39269.0, 44112.0, 48846.0, 39956.0, 40839.0, 21493.0, 57410.0, 23704.0, 35436.0, 26928.0, 41959.0, 29080.0, 49257.0, 19568.0, 37899.0, 21595.0, 31713.0, 25320.0, 29231.0, 31199.0, 25115.0, 24945.0, 28485.0, 29427.0, 24808.0, 59898.0, 71932.0, 54802.0, 40301.0, 46643.0, 25177.0, 25048.0, 88488.0, 51188.0, 51532.0, 35785.0, 49094.0, 55626.0, 20054.0, 43477.0, 22786.0, 25905.0, 23570.0, 16578.0, 46093.0, 13047.0, 21403.0, 23531.0, 24670.0, 32845.0, 21132.0, 53292.0, 63423.0, 57836.0, 51422.0, 25808.0, 32835.0, 55719.0, 21120.0, 53569.0, 26697.0, 22240.0, 35971.0, 42099.0, 22565.0, 34268.0, 19638.0, 25786.0, 38527.0, 87793.0, 64185.0, 59350.0, 40918.0, 35537.0, 29993.0, 29644.0, 53499.0, 67213.0, 42082.0, 44691.0, 54073.0, 52362.0, 65301.0, 50305.0, 50316.0, 50671.0, 35842.0, 28255.0, 26949.0, 62904.0, 28305.0, 32859.0, 84040.0, 29483.0, 55967.0, 36993.0, 50272.0, 68263.0, 53075.0, 79790.0, 35139.0, 40404.0, 38860.0, 28476.0, 18940.0, 20868.0, 24967.0, 21259.0, 23274.0, 28210.0, 21562.0, 63189.0, 54899.0, 57445.0, 84553.0, 89538.0, 45041.0, 24213.0, 44322.0, 79022.0, 87070.0, 34203.0, 89472.0, 64190.0, 88140.0, 14170.0, 14151.0, 14795.0, 14403.0, 40404.0, 13905.0, 14212.0, 14121.0, 14771.0, 14110.0, 14367.0, 14330.0, 48539.0, 45192.0, 47802.0, 52449.0, 42458.0, 82762.0, 84230.0, 68614.0, 42114.0, 82602.0, 70624.0, 31143.0, 60247.0, 68699.0, 83892.0, 54760.0, 53064.0, 53183.0, 55424.0, 64348.0, 77703.0, 53499.0, 67574.0, 65767.0, 32596.0, 50720.0, 55014.0, 54170.0, 58254.0, 88284.0, 84374.0, 51632.0, 56976.0, 69550.0, 51506.0, 80049.0, 82404.0, 52919.0, 74626.0, 85962.0, 50607.0, 57271.0, 38098.0, 82000.0, 53370.0, 82467.0, 64870.0, 85270.0, 41897.0, 55201.0, 65527.0, 24906.0, 26944.0, 27786.0, 18966.0, 28802.0, 30345.0, 30785.0, 30539.0, 28133.0, 23741.0, 26046.0, 24279.0, 28108.0, 25879.0, 27709.0, 28428.0, 28821.0, 27052.0, 25083.0, 29043.0, 21287.0, 28244.0, 19699.0, 29786.0, 84517.0, 40500.0, 84561.0, 9168.0, 37205.0, 87419.0, 36335.0, 78051.0, 65574.0, 31660.0, 70892.0, 23169.0, 51935.0, 34788.0, 41296.0, 47288.0, 62187.0, 49516.0, 39027.0, 79475.0, 87072.0, 23867.0, 17701.0, 62266.0, 16652.0, 47091.0, 35165.0, 55689.0, 65548.0, 34923.0, 49498.0, 44621.0, 28305.0, 50099.0, 57313.0, 55796.0, 47133.0, 38569.0, 20427.0, 21685.0, 26055.0, 23010.0, 21373.0, 26556.0, 26470.0, 26425.0, 49974.0, 26547.0, 49362.0, 17261.0, 45542.0, 65742.0, 33011.0, 33179.0, 48532.0, 30861.0, 87499.0, 56966.0, 57473.0, 23147.0, 19992.0, 20567.0, 38013.0, 33672.0, 20657.0, 19339.0, 25605.0, 23716.0, 31544.0, 20468.0, 26284.0, 53879.0, 43434.0, 28979.0, 55606.0, 51862.0, 33007.0, 57130.0, 85851.0, 49320.0, 21929.0, 28094.0, 32171.0, 35017.0, 64587.0, 61212.0, 27159.0, 54443.0, 65881.0, 53667.0, 81900.0, 54580.0, 30696.0, 47025.0, 40572.0, 65827.0, 30567.0, 87590.0, 32839.0, 50790.0, 45378.0, 49754.0, 53709.0, 30260.0, 38757.0, 21446.0, 49276.0, 49858.0, 46719.0, 44658.0, 87404.0, 47621.0, 53580.0, 30305.0, 30586.0, 68424.0, 48321.0, 21974.0, 44580.0, 48004.0, 26512.0, 50523.0, 47575.0, 25676.0, 43431.0, 57799.0, 75656.0, 24373.0, 65476.0, 21708.0, 44743.0, 46465.0, 19862.0, 26392.0, 18459.0, 26126.0, 21394.0, 21551.0, 18672.0, 39106.0, 15055.0, 28290.0, 48695.0, 47247.0, 28872.0, 50004.0, 21064.0, 20662.0, 18594.0, 33305.0, 23334.0, 64459.0, 26718.0, 30849.0, 58644.0, 79987.0, 65935.0, 47143.0, 27524.0, 31653.0, 34793.0, 70376.0, 72374.0, 21590.0, 73224.0, 86376.0, 27636.0, 38948.0, 52019.0, 67501.0, 25062.0, 41093.0, 43711.0, 71348.0, 62745.0, 57565.0, 64645.0, 83250.0, 83756.0, 49327.0, 83654.0, 57206.0, 27116.0, 61261.0, 58168.0, 26782.0, 59933.0, 82902.0, 76835.0, 67776.0, 27917.0, 55001.0, 50865.0, 85776.0, 52869.0, 45407.0, 81960.0, 55786.0, 90382.0, 40539.0, 43979.0, 26898.0, 71850.0, 32071.0, 57973.0, 29866.0, 47111.0, 48337.0, 83133.0, 44066.0, 66497.0, 80856.0, 28505.0, 64105.0, 55582.0, 59557.0, 55875.0, 26913.0, 53648.0, 71327.0, 65601.0, 40435.0, 77270.0, 57180.0, 39694.0, 18660.0, 66106.0, 43815.0, 89028.0, 46233.0, 38105.0, 52643.0, 51621.0, 38498.0, 59815.0, 67954.0, 56752.0, 69552.0, 56183.0, 30785.0, 25537.0, 75410.0, 84103.0, 40903.0, 53202.0, 64197.0, 76815.0, 45422.0, 84793.0, 42972.0, 44397.0, 28394.0, 53003.0, 70621.0, 56765.0, 39344.0, 37319.0, 87648.0, 69964.0, 60314.0, 80466.0, 17454.0, 34321.0, 81727.0, 61950.0, 70630.0, 29902.0, 23998.0, 50192.0, 44558.0, 32000.0, 36580.0, 39914.0, 32362.0, 33880.0, 33530.0, 35015.0, 25015.0, 45805.0, 43045.0, 35258.0, 38838.0, 55248.0, 23850.0, 76798.0, 27277.0, 40671.0, 30148.0, 46442.0, 42034.0, 60242.0, 21540.0, 24353.0, 31638.0, 26692.0, 30015.0, 25124.0, 25574.0, 30710.0, 72441.0, 55159.0, 21277.0, 25753.0, 43864.0, 48247.0, 34452.0, 22077.0, 25385.0, 24636.0, 34274.0, 24422.0, 22233.0, 22227.0, 62570.0, 31203.0, 31270.0, 49024.0, 48038.0, 43358.0, 55117.0, 27042.0, 39450.0, 37072.0, 38315.0, 34244.0, 49004.0, 23441.0, 19001.0, 35688.0, 41530.0, 24750.0, 54622.0, 25169.0, 24289.0, 71136.0, 71986.0, 38618.0, 39440.0, 25489.0, 33678.0, 23079.0, 25637.0, 25663.0, 41548.0, 43776.0, 58363.0, 89590.0, 59256.0, 23441.0, 33424.0, 61607.0, 74226.0, 53020.0, 25210.0, 52716.0, 34502.0, 68583.0, 44211.0, 23778.0, 23438.0, 45904.0, 50082.0, 24622.0, 20749.0, 21401.0, 26185.0, 46766.0, 25384.0, 48681.0, 25185.0, 22254.0, 15558.0, 51124.0, 41944.0, 46874.0, 43778.0, 22652.0, 25506.0, 26243.0, 42865.0, 16830.0, 23587.0, 26362.0, 79788.0, 66719.0, 45672.0, 25505.0, 48004.0, 47999.0, 85606.0, 34504.0, 67493.0, 25791.0, 28073.0, 35592.0, 24529.0, 24100.0, 24060.0, 32696.0, 25261.0, 31247.0, 29807.0, 19836.0, 24505.0, 76604.0, 20339.0, 50002.0, 23886.0, 22352.0, 27052.0, 27443.0, 57451.0, 22234.0, 68224.0, 36323.0, 23482.0, 19097.0, 22690.0, 25098.0, 33765.0, 25557.0, 57616.0, 87284.0, 65009.0, 85880.0, 67357.0, 69079.0, 54410.0, 25988.0, 35649.0, 53460.0, 42539.0, 58702.0, 43035.0, 32838.0, 33766.0, 52854.0, 56756.0, 54526.0, 28604.0, 70325.0, 46027.0, 58698.0, 31735.0, 42025.0, 34588.0, 50067.0, 45935.0, 31137.0, 57184.0, 26633.0, 29446.0, 28405.0, 63985.0, 45040.0, 80961.0, 54283.0, 51928.0, 34431.0, 43898.0, 26593.0, 36951.0, 38954.0, 39926.0, 34824.0, 27661.0, 29075.0, 51255.0, 87000.0, 28816.0, 60273.0, 24478.0, 28477.0, 73178.0, 31209.0, 50501.0, 62459.0, 78378.0, 62449.0, 56826.0, 72124.0, 45903.0, 27648.0, 32446.0, 30359.0, 78092.0, 68516.0, 31423.0, 50758.0, 21839.0, 46470.0, 20434.0, 44888.0, 20018.0, 22022.0, 18650.0, 19601.0, 19772.0, 23809.0, 48190.0, 26415.0, 42504.0, 51362.0, 42941.0, 71365.0, 52639.0, 50822.0, 53315.0, 50903.0, 48840.0, 69849.0, 37092.0, 44450.0, 66768.0, 53528.0, 62648.0, 49270.0, 56889.0, 63540.0, 59422.0, 45558.0, 18719.0, 21705.0, 19366.0, 19593.0, 48785.0, 19652.0, 18199.0, 22797.0, 19860.0, 28679.0, 22756.0, 21266.0, 19781.0, 20079.0, 24818.0, 14961.0, 16834.0, 12986.0, 12976.0, 18382.0, 20508.0, 11510.0, 14214.0, 12920.0, 16380.0, 16057.0, 16625.0, 16051.0, 16837.0, 16065.0, 16190.0, 16324.0, 14498.0, 17710.0, 12501.0, 19396.0, 15909.0, 19547.0, 21637.0, 17193.0, 15118.0, 14113.0, 19728.0, 23368.0, 14224.0, 17771.0, 87833.0, 24591.0, 42167.0, 31313.0, 83124.0, 35325.0, 24449.0, 32794.0, 21649.0, 27710.0, 30038.0, 30099.0, 70775.0, 40404.0, 38913.0, 11523.0, 55064.0, 40404.0, 26987.0, 22820.0, 40404.0, 38153.0, 26182.0, 40404.0, 16728.0, 46233.0, 20807.0, 18075.0, 38047.0, 23718.0, 23561.0, 86474.0, 15318.0, 31368.0, 55938.0, 55588.0, 40404.0, 22256.0, 39665.0, 46129.0, 31571.0, 49705.0, 35893.0, 22547.0, 24956.0, 18768.0, 54947.0, 31820.0, 18226.0, 40826.0, 40404.0, 53447.0, 29016.0, 21655.0, 19927.0, 24267.0, 52367.0, 27748.0, 21201.0, 23524.0, 19617.0, 18177.0, 19909.0, 24008.0, 52511.0, 35852.0, 32680.0, 15571.0, 25161.0, 26916.0]

college_df['Full-Time Retention Rate (median)'] = [0.6989, 0.8009, 0.7628, 0.8425, 0.6975, 0.8949, 0.6757, 0.9478, 0.6447, 0.6699, 0.6457, 0.6488, 0.5625, 0.7396, 0.7275, 0.7969, 0.7113, 0.9287, 0.7574, 0.7023, 0.5281, 0.5441, 0.7121, 0.8068, 0.7068, 0.7406, 0.8664, 0.8278, 0.7205, 0.7548, 0.7391, 0.5372, 0.7647, 0.234, 0.7131, 0.8637, 0.6416, 0.7812, 0.7331, 0.6275, 0.5385, 0.864, 0.6173, 0.7964, 0.8148, 0.8254, 0.6862, 0.6568, 0.7015, 0.6616, 0.7543, 0.8594, 0.8402, 0.839, 0.7436, 0.867, 0.7878, 0.9555, 0.7883, 0.8246, 0.7959, 0.8738, 0.8163, 0.7365, 0.8157, 0.8242, 0.7569, 0.868, 0.7185, 0.7344, 0.8191, 0.9679, 0.9281, 0.9405, 0.9731, 0.876, 0.9402, 0.93, 0.8795, 0.8239, 0.7746, 0.9181, 0.5, 0.7483, 0.8571, 0.9813, 0.6875, 0.25, 0.0, 0.8548, 0.7157, 0.9641, 0.7599, 1.0, 0.7302, 0.6445, 0.8421, 0.7729, 0.8467, 0.8858, 0.6994, 0.7114, 0.5263, 0.625, 0.8985, 0.7447, 0.5244, 0.7628, 0.8864, 0.8846, 0.8757, 0.938, 0.8554, 0.9755, 0.8402, 0.9063, 0.914, 0.827, 0.8369, 0.7688, 0.8684, 0.9392, 0.9382, 0.6042, 0.8537, 0.792, 0.7006, 0.9593, 0.9161, 0.0, 0.85, 0.6621, 0.7404, 0.5068, 0.7265, 0.6835, 0.9015, 0.8374, 0.9362, 0.9279, 0.8589, 0.5056, 0.8894, 0.6613, 0.7879, 0.6289, 0.5417, 0.7628, 0.7585, 0.7143, 0.5398, 0.6425, 0.7238, 0.6686, 0.6129, 0.7711, 1.0, 0.8973, 0.9246, 0.8374, 0.9129, 0.829, 0.5904, 0.7648, 0.3341, 0.8912, 0.8308, 0.8208, 0.7787, 0.8995, 0.9488, 0.7319, 0.9878, 0.6995, 0.9196, 0.7181, 0.6122, 0.882, 0.8651, 0.7114, 0.9223, 0.9675, 0.9088, 1.0, 0.6923, 0.45, 0.6337, 0.6175, 0.766, 0.9235, 0.7584, 0.8806, 0.8918, 0.8447, 0.7553, 0.756, 0.64, 0.7995, 0.9185, 0.4952, 0.8, 0.9605, 0.9771, 0.5309, 0.7467, 0.5, 0.9377, 0.8466, 0.7564, 0.6796, 0.8635, 0.8524, 0.5922, 0.9128, 0.5656, 0.7818, 0.6989, 0.8545, 0.5667, 0.28, 0.4392, 0.4118, 0.8876, 0.6917, 0.8133, 0.7857, 0.707, 0.8351, 0.6497, 0.4843, 0.5866, 0.7088, 0.6966, 0.8821, 0.709, 0.2222, 0.7094, 0.957, 0.7851, 0.9808, 0.5755, 0.8235, 0.7783, 0.7986, 0.9404, 0.6721, 0.6281, 0.8216, 0.8691, 0.7333, 0.6982, 0.6222, 0.8633, 0.7472, 0.6053, 0.4925, 0.625, 0.6698, 0.7187, 0.76, 0.775, 0.6461, 0.7037, 0.7275, 0.8072, 0.5645, 0.7795, 0.7885, 0.7198, 0.7559, 0.8185, 0.6105, 0.7741, 0.8383, 0.8211, 0.7706, 0.6721, 0.8265, 0.5732, 0.9926, 0.6603, 0.605, 0.855, 0.3711, 0.7171, 0.799, 0.5039, 0.5622, 0.7081, 0.8605, 0.8021, 0.6601, 0.948, 0.8005, 0.7063, 0.8596, 0.8144, 0.5917, 0.8313, 0.8988, 0.7915, 0.8167, 0.6735, 0.7628, 0.75, 0.7441, 0.839, 0.5042, 0.7713, 0.6166, 0.6962, 0.981, 0.5233, 0.7083, 0.7003, 0.6526, 0.6162, 0.7793, 0.7876, 0.7573, 0.748, 1.0, 0.668, 0.757, 0.8145, 0.125, 0.8824, 0.6137, 0.9259, 0.5993, 0.777, 0.724, 0.8749, 0.4228, 0.8858, 0.7723, 0.8333, 0.7294, 0.8013, 0.7737, 0.8182, 0.7039, 0.8381, 0.6657, 0.7219, 0.7104, 0.5941, 0.6585, 0.6934, 0.6509, 0.9106, 0.7136, 0.6377, 0.6176, 0.6632, 0.7588, 0.829, 0.4286, 0.9908, 0.7769, 0.9167, 0.7072, 0.6184, 0.881, 0.8929, 0.7994, 0.754, 0.9295, 0.6424, 0.7604, 0.7993, 0.6734, 0.727, 0.7953, 0.8465, 0.8409, 0.7656, 0.7662, 0.5504, 0.7015, 0.9256, 0.8757, 0.9036, 0.8228, 0.7699, 0.6129, 0.6923, 0.7418, 0.7277, 0.3473, 0.8166, 0.735, 0.7577, 0.8129, 0.6774, 0.4414, 0.7571, 0.5816, 0.658, 0.8323, 0.4253, 0.6188, 0.45, 0.7685, 0.7688, 0.5238, 0.6545, 0.8649, 0.6887, 0.8559, 0.6008, 0.7667, 0.6515, 0.6986, 0.583, 0.65, 0.559, 0.5035, 0.5271, 0.6803, 0.693, 0.5657, 0.8333, 0.7512, 0.7918, 0.6741, 0.645, 0.875, 0.743, 0.7693, 0.6906, 0.6369, 0.5256, 0.8684, 0.8608, 0.63, 0.8149, 0.6759, 0.6501, 0.7565, 0.7551, 0.6873, 0.6404, 0.6675, 0.8705, 0.6378, 0.7831, 0.702, 0.7805, 0.6608, 0.6952, 0.8474, 0.8315, 0.5243, 0.822, 0.8006, 0.6844, 0.6679, 0.766, 0.7275, 0.7087, 0.7097, 0.6393, 0.7253, 0.6031, 0.52, 0.7428, 0.9255, 0.7168, 0.85, 0.9129, 0.9683, 0.9365, 0.6, 0.7277, 0.8929, 0.8336, 0.8166, 0.5842, 0.7942, 0.7167, 0.7457, 0.7394, 0.7749, 0.3611, 0.6, 0.6819, 0.7681, 0.6408, 0.6622, 0.6928, 0.786, 0.6799, 0.9809, 0.8711, 0.5538, 0.8505, 0.962, 0.8339, 0.6179, 0.7334, 0.7077, 0.7277, 0.7766, 0.8575, 0.8271, 0.8277, 0.7879, 0.8391, 0.7602, 0.5673, 0.9734, 0.6032, 0.8392, 0.9457, 0.728, 0.9268, 0.8857, 0.75, 0.9602, 0.9472, 0.8702, 0.7512, 1.0, 0.8617, 0.6616, 0.6835, 0.5732, 0.8736, 0.7858, 0.8436, 0.5459, 0.6947, 0.7099, 0.8442, 0.7838, 0.983, 0.7143, 0.9478, 0.7038, 0.7228, 0.8399, 0.9191, 0.7041, 0.7396, 0.891, 0.9908, 0.868, 0.7927, 0.9091, 0.8859, 0.8842, 0.7246, 0.7566, 0.969, 0.7602, 0.7895, 0.7525, 0.8481, 0.943, 0.8067, 0.636, 0.8396, 0.7543, 0.955, 0.965, 0.8376, 0.7397, 0.739, 0.8218, 0.9685, 0.9366, 0.7814, 0.6542, 0.708, 0.8497, 0.8321, 0.7831, 0.661, 0.8676, 0.7536, 0.6585, 0.8217, 0.8205, 0.8349, 0.6875, 0.7762, 0.943, 0.6522, 0.7828, 0.7632, 0.4894, 0.8837, 0.8455, 0.788, 0.7836, 0.7154, 0.5957, 0.9747, 0.9005, 0.8882, 0.8249, 0.7778, 0.7796, 0.7862, 0.7794, 0.6138, 0.5897, 0.7757, 0.7, 0.7707, 0.8265, 0.8112, 0.0, 0.7233, 0.7267, 0.7196, 0.8571, 0.9647, 0.8356, 0.6739, 0.8467, 0.8798, 0.7823, 0.9228, 0.8025, 0.6754, 0.9112, 0.8, 0.7456, 0.8114, 0.739, 0.7496, 0.8221, 0.8287, 0.45, 0.8628, 0.7065, 0.8575, 0.7463, 0.9223, 0.6984, 0.8184, 0.8845, 0.8034, 0.7371, 0.7904, 0.7665, 0.6781, 0.6792, 0.6667, 0.6235, 0.5802, 0.8721, 0.6731, 0.6975, 0.7776, 0.825, 0.8438, 0.7209, 0.832, 0.7794, 0.7053, 0.5941, 0.0, 0.5455, 0.6875, 0.6184, 0.7363, 0.5, 0.7509, 0.6724, 0.672, 0.7917, 0.7636, 0.7833, 0.684, 0.7833, 0.5986, 0.6563, 0.5, 0.8467, 0.8148, 0.6534, 0.6278, 0.5297, 0.5379, 0.9268, 0.7536, 0.8656, 0.7361, 0.8474, 0.7392, 0.8345, 0.5762, 0.7628, 0.7912, 0.8784, 0.6923, 0.6482, 0.7838, 0.7576, 0.7725, 0.9495, 0.6866, 0.7097, 0.738, 0.5797, 0.8205, 0.5556, 0.7216, 0.7674, 0.7852, 0.7477, 0.6386, 0.6905, 0.8235, 0.7857, 0.5793, 0.6087, 0.7111, 0.6317, 0.7953, 0.9415, 0.7925, 0.6563, 0.7996, 0.8571, 0.6926, 0.7787, 0.75, 0.8599, 0.6445, 0.7978, 0.8354, 0.7239, 0.687, 0.7922, 0.7966, 0.7674, 0.9842, 0.7434, 0.6128, 0.6112, 0.8727, 0.7868, 0.6845, 0.7571, 0.8813, 0.88, 0.5455, 0.7726, 0.7784, 0.8837, 0.7698, 0.7571, 0.7611, 0.8234, 0.6482, 0.7607, 0.7986, 0.7789, 0.8954, 0.9835, 0.8361, 0.7836, 0.9302, 0.7178, 0.8145, 0.6471, 0.9364, 0.7859, 0.7628, 0.9132, 0.7394, 0.6203, 0.4977, 0.7703, 0.7617, 0.7338, 0.5506, 0.5805, 0.8286, 0.8582, 0.7752, 0.8458, 0.9657, 0.5517, 0.8649, 0.7262, 0.8478, 0.9343, 0.2, 0.98, 0.9194, 0.9838, 0.886, 0.8012, 0.757, 0.7926, 0.7628, 0.7765, 0.816, 0.7307, 0.4974, 0.6487, 0.7868, 0.5744, 0.7344, 0.7567, 0.6644, 0.6975, 0.6966, 0.8852, 0.9481, 0.7444, 0.638, 0.8636, 0.8362, 0.8398, 0.7693, 0.8467, 0.9789, 0.7336, 0.7333, 0.8355, 0.7719, 0.7598, 0.9296, 0.7387, 0.8609, 0.7018, 0.7572, 0.8517, 0.7363, 0.7305, 0.8482, 0.8476, 0.9577, 0.8038, 0.7799, 0.7549, 0.7519, 0.8826, 0.9072, 0.836, 0.8879, 0.9069, 0.7789, 0.8589, 0.6475, 0.9083, 0.7336, 0.8735, 0.8269, 0.8965, 0.807, 0.8642, 0.787, 0.6949, 0.5694, 0.6871, 0.8157, 0.8344, 0.8938, 0.8521, 0.8981, 0.8702, 0.6915, 0.7177, 0.5772, 0.8109, 0.7624, 0.8699, 0.8502, 0.7551, 0.7045, 0.7767, 0.8031, 0.7177, 0.732, 0.6571, 0.8346, 0.9013, 0.8883, 0.9018, 0.8446, 0.7071, 0.949, 0.7647, 0.8548, 0.8342, 0.7931, 0.9153, 0.8369, 0.6548, 0.7044, 0.8571, 0.6151, 0.7616, 0.773, 0.7081, 0.9461, 0.9793, 0.8272, 0.7688, 0.898, 0.7529, 0.5533, 0.6587, 0.6492, 0.8535, 0.7133, 0.6884, 0.7553, 0.7063, 0.6933, 0.7938, 0.651, 0.5888, 0.7165, 0.7752, 0.7209, 0.9661, 0.8498, 0.7891, 0.7271, 0.9276, 0.9447, 0.5854, 0.8816, 0.7358, 0.7164, 0.7231, 0.7406, 0.3158, 0.0, 0.6753, 0.5165, 0.9256, 0.7092, 0.7048, 0.7725, 0.7911, 0.6744, 0.6735, 0.8354, 0.8068, 0.6648, 0.8402, 0.7842, 0.6286, 0.7086, 0.7298, 0.5088, 0.7652, 0.7222, 0.8384, 0.5957, 0.8157, 0.7554, 0.9214, 0.8958, 0.5592, 0.6912, 0.8535, 0.6237, 0.878, 0.9024, 0.7032, 0.8032, 0.8906, 0.5565, 0.8852, 0.7374, 0.359, 0.7413, 0.7186, 0.8288, 0.8094, 0.9163, 0.7353, 0.5936, 0.8712, 0.7558, 0.6943, 0.8667, 0.9014, 0.8077, 0.7668, 0.7941, 0.6873, 0.7346, 0.91, 0.6396, 0.8433, 0.9423, 0.8389, 0.8474, 0.7992, 0.7199, 0.8748, 0.7158, 0.773, 0.7018, 0.7237, 0.7417, 0.7203, 0.6345, 0.8208, 0.6793, 0.7747, 0.7573, 0.5, 0.7286, 0.672, 0.6523, 0.6061, 0.5625, 0.5394, 0.605, 0.6507, 0.7252, 0.5591, 0.8478, 0.7166, 0.8391, 0.9, 0.8049, 0.6965, 0.663, 0.6343, 0.5789, 0.677, 0.9211, 0.7148, 0.6667, 0.8344, 0.8881, 0.7971, 0.759, 0.6898, 0.8776, 0.864, 0.6949, 0.7945, 0.7611, 0.8832, 0.8764, 0.6785, 0.9167, 0.777, 0.8651, 0.7274, 0.7333, 0.6167, 0.7794, 0.8303, 0.7198, 0.788, 0.9224, 0.9368, 0.8443, 0.98, 0.7097, 0.6471, 0.7781, 0.6243, 0.6852, 0.6928, 0.9198, 0.8951, 0.8415, 0.7213, 0.6547, 0.8372, 0.9024, 0.7617, 0.7846, 0.9121, 0.7752, 0.9383, 0.7773, 0.8303, 0.7534, 0.8333, 0.5723, 0.757, 0.7779, 0.6882, 0.739, 0.8967, 0.7939, 0.8298, 0.937, 0.7341, 0.7611, 0.7981, 0.7979, 0.8857, 0.7711, 0.7764, 0.8056, 0.7917, 0.5612, 0.8993, 0.7209, 0.9264, 0.7628, 0.0, 0.8511, 0.9888, 0.7662, 0.9199, 0.7394, 0.832, 0.8202, 0.8302, 0.8868, 0.8225, 0.8538, 0.8088, 0.7681, 0.8401, 0.8633, 0.9398, 0.8261, 0.7327, 0.8246, 0.8691, 0.7849, 0.9506, 0.8121, 0.7164, 0.8311, 0.8097, 0.7836, 0.7157, 0.7447, 0.7821, 0.9882, 0.8691, 0.8199, 0.9395, 0.7334, 0.8362, 0.9504, 0.8109, 0.8279, 0.4, 0.4497, 0.8186, 0.6314, 0.5732, 0.8245, 0.6899, 0.8196, 0.8578, 0.7549, 0.9347, 0.5814, 0.6941, 0.5327, 0.6042, 0.7964, 0.5578, 0.7002, 0.9061, 0.6961, 0.6409, 0.4127, 0.6925, 0.7249, 0.7955, 0.6678, 0.6126, 0.922, 0.7743, 0.5646, 0.6985, 0.5631, 0.7361, 0.9098, 0.8612, 0.7165, 0.7546, 0.7514, 0.6759, 0.3333, 0.7698, 0.8409, 0.8381, 0.745, 0.7934, 0.6997, 0.5263, 0.8694, 0.5392, 0.7105, 0.7417, 0.7487, 0.5947, 0.8357, 0.7572, 0.7381, 0.6122, 0.8587, 0.6941, 0.6012, 0.4426, 0.4724, 0.8227, 0.7167, 0.7717, 0.7129, 0.7738, 0.7952, 0.9232, 0.8886, 0.8281, 0.7202, 0.7252, 0.919, 0.7696, 0.335, 0.7816, 0.736, 0.6286, 0.89, 0.9634, 0.8051, 0.6864, 0.4124, 0.7939, 0.9095, 0.583, 0.5843, 0.6437, 0.4091, 0.7723, 0.7084, 0.6371, 0.5723, 0.6487, 0.6933, 0.7444, 0.6709, 0.651, 0.8699, 0.5174, 0.5819, 0.7129, 0.4765, 0.6187, 0.7783, 0.8078, 0.7032, 0.6242, 0.6352, 0.6393, 1.0, 0.7665, 0.6277, 0.8111, 0.4898, 0.7562, 0.9741, 0.7967, 0.777, 0.7325, 0.6679, 0.73, 0.9052, 0.7516, 0.806, 0.7169, 0.8008, 0.7267, 0.4491, 0.6985, 0.6459, 0.9431, 0.7294, 0.9674, 0.8995, 0.7894, 0.7678, 0.9287, 0.3403, 0.6181, 0.6093, 0.7984, 0.6621, 0.8495, 0.6082, 0.6955, 0.9287, 0.4453, 0.6963, 0.4958, 0.9097, 0.7354, 1.0, 0.8619, 0.7634, 0.8204, 0.817, 0.9366, 0.7926, 0.7994, 0.8571, 0.6783, 0.8918, 0.6525, 0.6149, 0.7529, 0.9456, 0.7458, 0.8124, 0.6627, 0.7609, 0.6414, 0.8599, 0.8368, 0.8534, 0.7396, 0.9198, 0.8013, 0.7977, 0.7061, 0.6678, 0.844, 0.7259, 0.7256, 0.7691, 0.7557, 0.8372, 0.745, 0.9075, 0.7571, 0.8174, 0.7401, 0.6934, 0.7157, 0.9308, 0.8534, 0.9755, 0.8098, 0.6939, 0.6657, 0.7425, 0.9661, 0.7005, 0.6933, 0.674, 0.6986, 0.929, 0.568, 0.8389, 0.8194, 0.8402, 0.6459, 0.7237, 0.8422, 0.8491, 0.7834, 0.9473, 0.7937, 0.8671, 0.776, 0.6571, 0.5375, 0.5484, 0.7479, 0.6484, 0.6522, 0.6739, 0.7218, 0.5476, 0.7138, 0.5673, 0.6886, 0.6732, 0.8343, 0.5366, 0.6096, 0.9464, 0.8056, 0.7825, 0.7339, 0.781, 0.7315, 0.6332, 0.8657, 0.8824, 0.6746, 0.9097, 0.795, 0.8378, 0.6725, 0.3107, 0.7231, 0.8367, 0.7619, 0.7804, 0.8175, 0.6591, 0.8651, 0.7251, 0.693, 0.6872, 0.789, 0.7183, 0.9616, 0.7295, 0.7903, 0.7645, 0.7383, 0.7968, 0.7661, 0.7952, 0.8175, 0.8, 0.8243, 0.8312, 1.0, 0.6858, 0.875, 0.7955, 0.8056, 0.713, 0.7323, 0.7643, 0.6865, 0.7628, 0.7387, 0.6905, 0.7612, 0.7784, 0.7148, 0.7593, 0.8133, 0.8701, 0.7304, 0.7718, 0.7505, 0.7907, 0.7832, 0.7514, 0.6859, 0.9818, 0.927, 0.5, 0.6515, 0.6301, 0.6222, 0.7557, 0.7699, 0.7864, 0.88, 0.7679, 0.6667, 0.8492, 0.8, 0.7365, 1.0, 0.9048, 0.625, 0.7987, 0.4167, 0.7628, 0.7143, 0.5484, 1.0, 0.6458, 0.6923, 0.8322, 0.5, 0.7411, 0.7877, 0.7243, 0.9796, 0.3026, 0.6667, 1.0, 0.7619, 0.7628, 0.3596, 0.8213, 0.7893, 0.4839, 0.6129, 0.7388, 0.6337, 0.6429, 0.9714, 0.9, 0.6667, 0.7099, 0.7273, 0.7628, 0.7857, 0.6471, 0.6567, 0.25, 1.0, 0.8507, 1.0, 0.74, 0.7556, 0.6529, 0.7347, 0.408, 0.7672, 0.8151, 0.7535, 0.5636, 0.657, 0.7757, 0.7169]

college_df['Four-Year Institution Graduation Rate (median)'] = [0.2403, 0.6423, 1.0, 0.6429, 0.3034, 0.7337, 0.326, 0.8195, 0.374, 0.4798, 0.5472, 0.347, 0.158, 0.5685, 0.541, 0.5491, 0.4462, 0.7704, 0.5267, 0.521, 0.25, 0.3091, 0.503, 0.5498, 0.2971, 0.3801, 0.6804, 0.6752, 0.4346, 0.6132, 0.5556, 0.3987, 0.4165, 0.0739, 0.4676, 0.7052, 0.4043, 0.554, 0.5353, 0.3411, 0.3585, 0.6879, 0.3734, 0.7235, 0.7179, 0.614, 0.5148, 0.3038, 0.2564, 0.4882, 0.3432, 0.7917, 0.6179, 0.676, 0.6188, 0.6122, 0.696, 0.864, 0.498, 0.5345, 0.549, 0.6843, 0.6278, 0.4279, 0.5696, 0.7018, 0.4795, 0.6888, 0.5298, 0.5695, 0.5629, 0.9284, 0.8567, 0.8687, 0.9262, 0.7596, 0.8605, 0.8303, 0.7509, 0.6667, 0.5972, 0.8188, 0.2963, 0.5831, 0.1967, 0.9136, 0.2874, 0.3723, 0.8, 0.7805, 0.5, 0.9188, 0.4855, 0.6154, 0.404, 0.6312, 0.5172, 0.5973, 0.6773, 0.7887, 0.535, 0.5325, 0.4286, 0.619, 0.8088, 0.663, 0.4944, 0.5612, 0.5828, 0.6905, 0.8335, 0.8339, 0.7717, 0.932, 0.6727, 0.7643, 0.8367, 0.5037, 0.7006, 0.5598, 0.6922, 0.8792, 0.8254, 0.4884, 0.703, 0.5759, 0.5677, 0.9183, 0.843, 0.5612, 0.7035, 0.5996, 0.6, 0.3942, 0.4615, 0.4693, 0.7419, 0.6441, 0.8766, 0.8171, 0.6651, 0.1878, 0.756, 0.3564, 0.4061, 0.3154, 0.3667, 0.5612, 0.5124, 0.6102, 0.3176, 0.3973, 0.505, 0.5148, 0.4119, 0.4844, 0.6667, 0.8205, 0.8329, 0.5752, 0.843, 0.5438, 0.4218, 0.6307, 0.2493, 0.757, 0.7346, 0.6376, 0.4993, 0.8377, 0.9264, 0.5176, 0.9574, 0.391, 0.8055, 0.5743, 0.1982, 0.7549, 0.7947, 0.4726, 0.8398, 0.9481, 0.6996, 0.0, 0.4929, 0.5185, 0.3787, 0.3052, 0.5206, 0.7801, 0.6592, 0.6655, 0.5335, 0.6257, 0.5598, 0.5404, 0.3889, 0.6354, 0.7443, 0.311, 0.7055, 0.8561, 0.9112, 0.4433, 0.5065, 0.5612, 0.8368, 0.6921, 0.6334, 0.5534, 0.7207, 0.7505, 0.45, 0.7676, 0.4806, 0.6229, 0.4255, 0.637, 0.3418, 0.0, 0.4213, 0.2796, 0.588, 0.3615, 0.7068, 0.3105, 0.4902, 0.6949, 0.3291, 0.2103, 0.2559, 0.3986, 0.4176, 0.7149, 0.2531, 0.0909, 0.4228, 0.9109, 0.4111, 0.9402, 0.4064, 0.6361, 0.549, 0.5306, 0.8969, 0.4692, 0.3793, 0.6962, 0.5944, 0.541, 0.4741, 0.4357, 0.6941, 0.2804, 0.3769, 0.2754, 0.4366, 0.3781, 0.4236, 0.4452, 0.4349, 0.4175, 0.554, 0.4837, 0.6429, 0.3489, 0.4955, 0.602, 0.3939, 0.5728, 0.6254, 0.4017, 0.7076, 0.6699, 0.7286, 0.6032, 0.5749, 0.7617, 0.1549, 0.9585, 0.5155, 0.3646, 0.678, 0.1556, 0.4736, 0.7, 0.4161, 0.2211, 0.3982, 0.5, 0.6162, 0.5033, 0.8513, 0.747, 0.6382, 0.7521, 0.6454, 0.5987, 0.6773, 0.7778, 0.6661, 0.7304, 0.5333, 0.2, 0.5494, 0.6461, 0.6233, 0.3014, 0.64, 0.5772, 0.4866, 0.9513, 0.2165, 0.6084, 0.4504, 0.472, 0.3514, 0.5526, 0.6682, 0.5661, 0.5321, 0.5612, 0.6241, 0.5697, 0.5752, 0.461, 0.6667, 0.4522, 0.8475, 0.5379, 0.6234, 0.5322, 0.8038, 0.2286, 0.7469, 0.69, 0.6446, 0.603, 0.65, 0.6877, 0.6713, 0.7289, 0.636, 0.3627, 0.5445, 0.5582, 0.4779, 0.4288, 0.4561, 0.4009, 0.8021, 0.3738, 0.3919, 0.3958, 0.4608, 0.6722, 0.6671, 0.0, 0.9517, 0.6552, 0.7816, 0.5497, 0.4663, 0.6933, 0.7381, 0.6438, 0.7037, 0.7701, 0.4751, 0.6169, 0.6619, 0.5612, 0.659, 0.6182, 0.7014, 0.7403, 0.4008, 0.6753, 0.4195, 0.5399, 0.8812, 0.7532, 0.7463, 0.676, 0.7112, 0.5, 0.6552, 0.5014, 0.5774, 0.1068, 0.6792, 0.6605, 0.6103, 0.6333, 0.3389, 0.2114, 0.643, 0.3262, 0.5779, 0.6158, 0.3574, 0.4112, 0.2697, 0.561, 0.477, 0.3226, 0.4335, 0.6881, 0.5281, 0.7108, 0.4863, 0.4429, 0.3392, 0.5361, 0.279, 0.4776, 0.3568, 0.4129, 0.3374, 0.5296, 0.5103, 0.3892, 0.6498, 0.6436, 0.5822, 0.5371, 0.4201, 0.8067, 0.5043, 0.5004, 0.4885, 0.319, 0.468, 0.7142, 0.3667, 0.4406, 0.6123, 0.4069, 0.5219, 0.6132, 0.5224, 0.4167, 0.5167, 0.405, 0.7148, 0.3213, 0.5556, 0.5621, 0.4328, 0.3616, 0.3422, 0.6881, 0.3754, 0.4387, 0.6382, 0.5903, 0.4704, 0.3799, 0.538, 0.542, 0.432, 0.4857, 0.4545, 0.4541, 0.2709, 0.1311, 0.5263, 0.8614, 0.4855, 0.6829, 0.8969, 0.9528, 0.8879, 0.2698, 0.5154, 0.3944, 0.5494, 0.5818, 0.5155, 0.6835, 0.5155, 0.6574, 0.4035, 0.5369, 0.2867, 0.3816, 0.382, 0.4268, 0.2865, 0.2622, 0.4966, 0.5734, 0.569, 0.9378, 0.7919, 0.3333, 0.7001, 0.8859, 0.7224, 0.3533, 0.4087, 0.6539, 0.5, 0.6815, 0.6995, 0.7143, 0.6946, 0.6849, 0.6537, 0.6329, 0.4591, 0.939, 0.4623, 0.7523, 0.9312, 0.4394, 0.8679, 0.6731, 0.3158, 0.9083, 0.8866, 0.8603, 0.5341, 0.1111, 0.7694, 0.5112, 0.5359, 0.3929, 0.7711, 0.6751, 0.7556, 0.2775, 0.5512, 0.478, 0.6854, 0.5426, 0.9758, 0.4444, 0.8733, 0.5864, 0.5802, 0.6482, 0.8326, 0.4941, 0.6202, 0.6887, 0.9641, 0.7406, 0.7005, 0.5347, 0.8439, 0.7339, 0.6261, 0.5564, 0.9054, 0.6809, 0.7217, 0.4977, 0.7234, 0.8905, 0.7419, 0.5207, 0.76, 0.6088, 0.9351, 0.9153, 0.6824, 0.6398, 0.5441, 0.7282, 0.9361, 0.8971, 0.6145, 0.4842, 0.6159, 0.6287, 0.7153, 0.6536, 0.3583, 0.7406, 0.5872, 0.4146, 0.7061, 0.5659, 0.672, 0.4644, 0.4687, 0.708, 0.5104, 0.6187, 0.6701, 0.36, 0.7995, 0.7598, 0.5098, 0.6058, 0.6, 0.4412, 0.932, 0.8072, 0.6806, 0.5798, 0.4031, 0.5214, 0.6332, 0.5756, 0.3527, 0.5, 0.4825, 0.3862, 0.6354, 0.5844, 0.5757, 0.36, 0.5167, 0.4787, 0.5486, 0.7138, 0.896, 0.6107, 0.459, 0.715, 0.7665, 0.6045, 0.871, 0.5395, 0.4357, 0.8528, 0.4976, 0.5116, 0.6472, 0.625, 0.5732, 0.6634, 0.6813, 0.2273, 0.7712, 0.4032, 0.7538, 0.6601, 0.84, 0.4539, 0.7053, 0.7638, 0.6125, 0.451, 0.5694, 0.5736, 0.4854, 0.5476, 0.4806, 0.5091, 0.5714, 0.7174, 0.4677, 0.2676, 0.5934, 0.6667, 0.1179, 0.4906, 0.3311, 0.5978, 0.5238, 0.4444, 1.0, 0.5217, 0.2195, 0.5123, 0.5408, 1.0, 0.4219, 0.5625, 0.3916, 0.618, 0.6503, 0.5039, 0.2756, 0.5797, 0.2085, 0.4933, 0.2222, 0.6622, 0.4828, 0.4758, 0.4158, 0.2244, 0.3854, 0.7494, 0.5546, 0.6437, 0.5664, 0.6853, 0.5423, 0.6364, 0.3843, 0.1429, 0.7456, 0.7953, 0.6168, 0.5532, 0.4274, 0.5793, 0.5791, 0.9426, 0.6439, 0.5549, 0.6766, 0.4681, 0.6929, 0.3004, 0.2794, 0.5824, 0.5708, 0.4796, 0.4111, 0.4841, 0.2762, 0.5125, 0.3295, 0.4667, 0.7, 0.5041, 0.6489, 0.8336, 0.5714, 0.4885, 0.5774, 0.5952, 0.4212, 0.4708, 0.6612, 0.6697, 0.3761, 0.605, 0.5226, 0.5215, 0.5221, 0.5051, 0.6124, 0.5745, 0.9554, 0.5351, 0.3451, 0.4283, 0.7607, 0.6006, 0.5203, 0.5167, 0.8003, 0.625, 0.4371, 0.5749, 0.5605, 0.7048, 0.5332, 0.4722, 0.5357, 0.6736, 0.3389, 0.4657, 0.719, 0.6466, 0.7276, 0.9761, 0.6981, 0.6133, 0.8363, 0.5826, 0.6949, 0.511, 0.8688, 0.6854, 0.5612, 0.8585, 0.4396, 0.4509, 0.2618, 0.5705, 0.5469, 0.5517, 0.1698, 0.3223, 0.6715, 0.6754, 0.5698, 0.6756, 0.9302, 0.4401, 0.806, 0.6639, 0.7491, 0.9117, 0.4, 0.961, 0.8111, 0.9538, 0.7212, 0.5386, 0.3393, 0.5682, 0.5612, 0.5686, 0.5583, 0.5128, 0.1977, 0.2147, 0.5325, 0.3225, 0.6749, 0.5888, 0.5251, 0.6471, 0.5532, 0.8191, 0.9063, 0.5332, 0.5631, 0.7725, 0.6854, 0.6522, 0.56, 0.7623, 0.9256, 0.5836, 0.5087, 0.7313, 0.5707, 0.6371, 0.7832, 0.5842, 0.796, 0.4904, 0.4571, 0.6993, 0.6546, 0.5683, 0.7279, 0.6937, 0.8757, 0.7451, 0.5877, 0.6003, 0.5055, 0.7354, 0.8362, 0.6667, 0.6989, 0.8543, 0.561, 0.6673, 0.5464, 0.7906, 0.5404, 0.7133, 0.7473, 0.8257, 0.6878, 0.7417, 0.6609, 0.3845, 0.4543, 0.4234, 0.5278, 0.6145, 0.8162, 0.7518, 0.7556, 0.6632, 0.5508, 0.5513, 0.3331, 0.6803, 0.5021, 0.7145, 0.716, 0.6881, 0.6036, 0.453, 0.6277, 0.4457, 0.5851, 0.4123, 0.6439, 0.8361, 0.7239, 0.8039, 0.8238, 0.5624, 0.9108, 0.3145, 0.7568, 0.6514, 0.3765, 0.832, 0.7453, 0.4585, 0.4668, 0.25, 0.4884, 0.6096, 0.4729, 0.2995, 0.9107, 0.9678, 0.6262, 0.4351, 0.8404, 0.3846, 0.5539, 0.462, 0.4581, 0.737, 0.3429, 0.4208, 0.4778, 0.2819, 0.4487, 0.7007, 0.4351, 0.5031, 0.5178, 0.5718, 0.5448, 0.9117, 0.6897, 0.5631, 0.4165, 0.7778, 0.8476, 0.4197, 0.7059, 0.4481, 0.4354, 0.3497, 0.6131, 0.2075, 0.25, 0.5743, 0.2179, 0.8915, 0.42, 0.4635, 0.4668, 0.6026, 0.506, 0.4904, 0.666, 0.406, 0.4505, 0.6048, 0.6389, 0.4595, 0.5333, 0.5186, 0.4127, 0.6063, 0.5333, 0.6677, 0.5294, 0.6373, 0.6027, 0.8717, 0.7253, 0.2281, 0.5571, 0.7496, 0.3394, 0.5771, 0.7213, 0.5057, 0.556, 0.8018, 0.3057, 0.789, 0.5786, 0.1111, 0.5198, 0.5451, 0.7855, 0.6372, 0.8234, 0.6512, 0.3795, 0.3246, 0.4498, 0.6138, 0.5581, 0.7979, 0.5385, 0.5865, 0.6811, 0.5633, 0.5637, 0.8089, 0.4102, 0.7548, 0.8772, 0.6545, 0.5857, 0.6788, 0.4811, 0.7545, 0.3987, 0.5704, 0.6667, 0.585, 0.1202, 0.4727, 0.5269, 0.7394, 0.4169, 0.6865, 0.5048, 0.3476, 0.5051, 0.3067, 0.3676, 0.3442, 0.2639, 0.1684, 0.3536, 0.3035, 0.5551, 0.2094, 0.6817, 0.5237, 0.6488, 0.7533, 0.5683, 0.2896, 0.4413, 0.3154, 0.1613, 0.3969, 0.7229, 0.43, 0.5172, 0.7196, 0.7536, 0.7046, 0.56, 0.5378, 0.7011, 0.7169, 0.2913, 0.6698, 0.5266, 0.7984, 0.7147, 0.4253, 0.4918, 0.6059, 0.7124, 0.4712, 0.6774, 0.507, 0.7255, 0.722, 0.5553, 0.6674, 0.8179, 0.8632, 0.5992, 0.9413, 0.6039, 0.5091, 0.6306, 0.4878, 0.4059, 0.5591, 0.7978, 0.7816, 0.7749, 0.4312, 0.54, 0.7617, 0.8377, 0.6636, 0.6098, 0.8253, 0.5688, 0.8964, 0.6091, 0.7104, 0.5551, 0.735, 0.3587, 0.5989, 0.5382, 0.5721, 0.5712, 0.8759, 0.6667, 0.6496, 0.8791, 0.4355, 0.5963, 0.7165, 0.6017, 0.7496, 0.5763, 0.7171, 0.5714, 0.7169, 0.5691, 0.8223, 0.5368, 0.8609, 0.1, 0.5758, 0.6852, 0.9654, 0.5968, 0.855, 0.5854, 0.6569, 0.5714, 0.7439, 0.7884, 0.6859, 0.7979, 0.6736, 0.557, 0.6557, 0.8174, 0.9227, 0.7505, 0.4873, 0.6857, 0.7328, 0.4904, 0.9186, 0.6952, 0.6554, 0.7051, 0.6455, 0.6832, 0.6317, 0.4815, 0.641, 0.9569, 0.7975, 0.5541, 0.8582, 0.4813, 0.7331, 0.8877, 0.6865, 0.7688, 0.5435, 0.1331, 0.6568, 0.4724, 0.2426, 0.6475, 0.5236, 0.6583, 0.75, 0.516, 0.8656, 0.1405, 0.3953, 0.4679, 0.3688, 0.6154, 0.4518, 0.4339, 0.7876, 0.4977, 0.3533, 0.1735, 0.4514, 0.5453, 0.5146, 0.3985, 0.3399, 0.7882, 0.4846, 0.3663, 0.4304, 0.4295, 0.5698, 0.842, 0.7297, 0.4263, 0.513, 0.4832, 0.5238, 0.0, 0.4894, 0.5295, 0.6235, 0.6291, 0.5991, 0.4024, 0.398, 0.7066, 0.3505, 0.4974, 0.5324, 0.5471, 0.4559, 0.7216, 0.5321, 0.2993, 0.5342, 0.7078, 0.5677, 0.4787, 0.1839, 0.2703, 0.6259, 0.4966, 0.369, 0.5, 0.5089, 0.537, 0.8453, 0.7979, 0.4939, 0.4759, 0.5024, 0.7392, 0.5254, 0.3399, 0.5767, 0.5315, 0.2545, 0.6596, 0.9354, 0.5901, 0.4397, 0.1944, 0.6705, 0.7999, 0.446, 0.4015, 0.5701, 0.2857, 0.7307, 0.4712, 0.2957, 0.4281, 0.4604, 0.4912, 0.5163, 0.332, 0.2638, 0.6456, 0.2798, 0.3394, 0.5098, 0.1519, 0.3732, 0.4647, 0.5858, 0.5136, 0.4931, 0.4429, 0.4274, 0.5417, 0.6071, 0.4611, 0.509, 0.2687, 0.432, 0.9464, 0.6259, 0.6877, 0.5476, 0.4318, 0.5893, 0.8427, 0.4156, 0.7279, 0.5333, 0.5528, 0.5234, 0.2994, 0.4821, 0.4187, 0.8391, 0.5402, 0.889, 0.7569, 0.5017, 0.5413, 0.8551, 0.1375, 0.5385, 0.3967, 0.5264, 0.2216, 0.6869, 0.3154, 0.4906, 0.8397, 0.1929, 0.5504, 0.2424, 0.8098, 0.5264, 0.48, 0.6505, 0.6381, 0.7121, 0.6523, 0.914, 0.6021, 0.7277, 0.3158, 0.4722, 0.7859, 0.4814, 0.1778, 0.5305, 0.8942, 0.5692, 0.7164, 0.5634, 0.67, 0.319, 0.6784, 0.6217, 0.5716, 0.6465, 0.7972, 0.6533, 0.6123, 0.5736, 0.393, 0.6641, 0.5351, 0.385, 0.4632, 0.4866, 0.7048, 0.4639, 0.852, 0.6736, 0.6682, 0.3347, 0.5182, 0.4706, 0.8622, 0.6318, 0.956, 0.7621, 0.3944, 0.3415, 0.4164, 0.9388, 0.5361, 0.5643, 0.4349, 0.4074, 0.8629, 0.5368, 0.7078, 0.6857, 0.6799, 0.519, 0.6195, 0.7551, 0.599, 0.605, 0.8518, 0.6464, 0.8052, 0.7089, 0.7105, 0.4682, 0.37, 0.4555, 0.3897, 0.3929, 0.4425, 0.5123, 0.1992, 0.5103, 0.3918, 0.5953, 0.5714, 0.6466, 0.2333, 0.4918, 0.6304, 0.7105, 0.707, 0.6426, 0.6835, 0.6024, 0.4245, 0.7677, 0.6357, 0.4416, 0.8321, 0.6695, 0.6711, 0.4296, 0.4966, 0.633, 0.7129, 0.6838, 0.589, 0.6381, 0.4822, 0.7096, 0.6357, 0.4614, 0.404, 0.5486, 0.4188, 0.8955, 0.4932, 0.5576, 0.57, 0.5078, 0.5884, 0.369, 0.3636, 0.3941, 0.3438, 0.6703, 0.4859, 0.3889, 0.3085, 0.6667, 0.4316, 0.4288, 0.3892, 0.3802, 0.3881, 0.4144, 0.3767, 0.3492, 0.4633, 0.52, 0.3706, 0.3727, 0.4983, 0.4712, 0.491, 0.4618, 0.5026, 0.3426, 0.5207, 0.2808, 0.314, 0.2823, 0.9192, 0.831, 0.7407, 0.4423, 0.4302, 0.4286, 0.6667, 0.3514, 0.5456, 0.418, 0.5769, 0.5135, 0.6023, 0.3333, 0.6136, 0.4, 0.9182, 0.3333, 0.5909, 0.2, 0.5, 0.8889, 0.3412, 0.5, 0.4618, 0.3019, 0.574, 0.4737, 0.3846, 0.3358, 0.5132, 0.9639, 0.4304, 0.25, 0.3125, 0.6095, 0.5612, 0.0851, 0.6872, 0.5394, 0.4, 0.4127, 0.3387, 0.2147, 0.8481, 0.5716, 1.0, 0.2286, 0.3328, 0.4167, 0.0, 0.2, 0.2857, 0.4017, 0.3303, 0.0, 0.6386, 0.5, 0.5612, 0.4881, 0.2533, 0.3729, 0.2084, 0.522, 0.6343, 0.5935, 0.2155, 0.4291, 0.5448, 0.5188]

college_df['Median Earnings 4 Years Post-Graduation (median)'] = 54018.0, 64969.0, 50075.0, 81045.0, 45998.0, 70439.0, 55551.0, 73151.0, 52824.0, 51132.0, 55318.0, 64122.0, 59521.0, 46865.0, 46262.0, 50818.0, 50714.0, 66567.0, 62459.0, 59521.0, 42622.0, 39579.0, 55048.0, 69077.0, 68777.0, 67252.0, 66968.0, 67420.0, 74343.0, 60629.0, 49339.0, 51181.0, 58470.0, 39577.0, 59521.0, 68890.0, 46380.0, 56631.0, 52203.0, 46683.0, 48062.0, 53024.0, 47583.0, 50422.0, 55210.0, 49862.0, 46099.0, 42151.0, 41389.0, 49008.0, 50255.0, 74009.0, 71925.0, 61363.0, 68600.0, 53517.0, 69695.0, 90662.0, 59109.0, 58952.0, 55441.0, 71138.0, 65228.0, 58922.0, 59992.0, 63753.0, 72596.0, 63140.0, 59756.0, 59664.0, 64511.0, 96018.0, 73086.0, 74438.0, 77677.0, 64926.0, 83130.0, 70323.0, 67085.0, 35256.0, 108757.0, 73336.0, 112516.0, 83064.0, 50741.0, 110798.0, 56708.0, 38025.0, 59521.0, 95437.0, 63285.0, 137100.0, 51571.0, 56489.0, 47070.0, 64109.0, 48922.0, 57898.0, 55487.0, 78039.0, 79903.0, 79546.0, 81115.0, 74029.0, 68467.0, 50900.0, 53687.0, 56852.0, 88027.0, 81820.0, 84459.0, 69786.0, 72880.0, 77544.0, 75863.0, 68268.0, 85309.0, 67804.0, 91483.0, 55374.0, 89614.0, 108517.0, 75301.0, 59198.0, 74325.0, 65997.0, 65874.0, 95739.0, 49755.0, 83334.0, 64044.0, 57988.0, 66794.0, 52621.0, 74059.0, 62980.0, 76850.0, 58576.0, 56959.0, 100252.0, 67911.0, 60707.0, 78504.0, 46601.0, 58601.0, 60186.0, 41627.0, 50282.0, 56930.0, 81785.0, 41363.0, 55898.0, 50666.0, 63088.0, 60311.0, 67245.0, 62128.0, 67540.0, 78925.0, 57759.0, 91378.0, 69078.0, 44062.0, 65164.0, 60571.0, 84363.0, 79431.0, 73035.0, 59787.0, 83645.0, 72119.0, 60346.0, 112971.0, 56957.0, 77675.0, 52348.0, 69354.0, 79081.0, 79320.0, 55195.0, 95967.0, 119773.0, 72974.0, 68449.0, 64019.0, 40595.0, 73480.0, 46007.0, 53587.0, 61355.0, 48651.0, 93582.0, 52657.0, 59690.0, 52031.0, 46022.0, 79607.0, 90403.0, 62192.0, 46572.0, 58753.0, 66924.0, 77321.0, 40367.0, 77058.0, 66268.0, 85019.0, 59418.0, 81582.0, 54983.0, 49311.0, 65488.0, 58644.0, 62079.0, 70806.0, 57773.0, 50572.0, 62720.0, 47042.0, 35285.0, 50390.0, 50359.0, 67723.0, 53386.0, 52746.0, 54096.0, 47337.0, 58750.0, 61654.0, 59521.0, 52505.0, 54430.0, 60912.0, 48802.0, 52160.0, 68975.0, 42976.0, 90139.0, 44844.0, 119180.0, 62132.0, 62852.0, 62342.0, 58898.0, 74144.0, 62232.0, 51860.0, 71870.0, 61320.0, 52138.0, 65743.0, 53795.0, 47980.0, 46912.0, 54008.0, 63556.0, 39953.0, 47336.0, 56067.0, 52803.0, 58022.0, 43173.0, 59437.0, 49763.0, 61903.0, 58128.0, 53969.0, 64791.0, 58142.0, 60330.0, 52628.0, 58274.0, 60040.0, 45385.0, 60377.0, 64521.0, 46015.0, 74150.0, 56486.0, 127757.0, 47092.0, 71699.0, 73466.0, 43920.0, 53620.0, 63784.0, 49625.0, 56405.0, 47578.0, 59521.0, 72839.0, 72460.0, 79628.0, 69265.0, 50691.0, 91312.0, 62507.0, 56385.0, 49217.0, 62893.0, 66586.0, 73865.0, 60630.0, 75504.0, 54115.0, 51368.0, 46905.0, 63065.0, 61656.0, 65399.0, 64583.0, 109275.0, 60607.0, 64769.0, 59724.0, 59145.0, 58796.0, 59507.0, 75229.0, 66961.0, 63235.0, 82776.0, 61484.0, 65199.0, 57170.0, 51985.0, 55437.0, 57453.0, 57675.0, 54833.0, 57619.0, 53289.0, 73732.0, 57530.0, 70091.0, 44750.0, 59762.0, 53224.0, 55539.0, 49126.0, 56221.0, 46024.0, 52242.0, 56455.0, 64616.0, 63673.0, 61150.0, 57688.0, 54618.0, 55103.0, 74511.0, 59535.0, 54129.0, 58030.0, 52989.0, 72150.0, 68838.0, 49801.0, 100684.0, 57090.0, 97780.0, 62831.0, 47647.0, 69406.0, 51779.0, 67814.0, 69228.0, 68626.0, 61163.0, 50318.0, 55693.0, 59490.0, 57133.0, 48353.0, 57567.0, 65232.0, 59598.0, 35449.0, 63607.0, 57521.0, 58955.0, 68277.0, 69866.0, 55860.0, 55033.0, 59521.0, 68691.0, 61955.0, 61330.0, 56883.0, 54830.0, 55312.0, 67026.0, 56509.0, 58837.0, 67834.0, 58373.0, 53878.0, 69904.0, 55405.0, 45971.0, 55094.0, 55610.0, 53751.0, 56419.0, 42262.0, 57698.0, 69680.0, 56857.0, 64711.0, 53289.0, 39200.0, 50934.0, 67555.0, 62228.0, 67112.0, 64687.0, 44980.0, 47989.0, 56774.0, 59707.0, 42268.0, 45728.0, 64564.0, 42924.0, 51492.0, 47650.0, 64933.0, 51882.0, 54691.0, 54370.0, 46766.0, 45592.0, 65922.0, 52466.0, 43852.0, 67853.0, 54588.0, 50224.0, 50487.0, 58429.0, 55132.0, 64136.0, 70208.0, 50923.0, 52077.0, 53602.0, 49479.0, 48421.0, 47043.0, 51983.0, 66893.0, 51673.0, 53861.0, 61520.0, 52459.0, 53563.0, 56037.0, 51767.0, 53715.0, 56762.0, 62842.0, 63699.0, 50215.0, 54666.0, 47240.0, 58638.0, 73816.0, 49328.0, 32352.0, 70028.0, 79722.0, 77429.0, 51475.0, 44430.0, 74979.0, 63056.0, 113298.0, 48577.0, 71281.0, 40550.0, 73164.0, 60816.0, 54264.0, 45016.0, 67949.0, 65066.0, 104028.0, 74717.0, 63359.0, 58511.0, 57036.0, 70173.0, 117419.0, 81772.0, 87025.0, 74396.0, 84365.0, 42353.0, 55733.0, 62308.0, 64424.0, 75732.0, 61985.0, 60029.0, 45787.0, 65610.0, 66853.0, 58768.0, 65855.0, 71565.0, 79243.0, 74347.0, 67745.0, 117794.0, 62912.0, 108577.0, 41028.0, 79953.0, 96145.0, 83615.0, 76742.0, 59669.0, 61712.0, 63965.0, 72447.0, 41151.0, 57731.0, 55925.0, 63280.0, 69414.0, 57557.0, 63994.0, 61569.0, 57638.0, 36500.0, 134794.0, 50999.0, 84553.0, 58411.0, 55117.0, 81163.0, 78620.0, 69532.0, 93192.0, 45607.0, 161961.0, 103680.0, 65506.0, 35321.0, 54450.0, 33743.0, 64532.0, 48835.0, 101903.0, 64421.0, 84660.0, 62605.0, 73823.0, 57618.0, 60428.0, 69251.0, 73137.0, 74456.0, 97474.0, 72449.0, 95027.0, 76928.0, 59434.0, 57982.0, 80487.0, 105724.0, 63801.0, 55233.0, 55297.0, 55040.0, 60517.0, 51578.0, 53754.0, 60889.0, 61298.0, 67914.0, 47659.0, 69009.0, 78953.0, 59616.0, 64721.0, 99943.0, 43821.0, 53010.0, 60491.0, 59521.0, 60573.0, 55566.0, 56687.0, 90760.0, 61516.0, 50000.0, 96159.0, 74093.0, 84560.0, 77294.0, 65600.0, 52624.0, 67409.0, 68708.0, 52261.0, 38046.0, 63454.0, 62131.0, 55203.0, 68551.0, 62885.0, 86185.0, 68350.0, 60307.0, 47456.0, 70633.0, 66841.0, 56802.0, 68250.0, 49182.0, 61015.0, 61017.0, 58560.0, 64235.0, 67658.0, 71941.0, 62786.0, 41825.0, 66056.0, 51631.0, 55083.0, 47587.0, 57471.0, 39785.0, 63895.0, 59194.0, 72829.0, 72502.0, 56323.0, 50863.0, 75595.0, 82136.0, 65829.0, 55009.0, 60533.0, 45495.0, 51795.0, 40841.0, 47248.0, 47606.0, 67303.0, 66243.0, 62987.0, 40972.0, 55434.0, 59311.0, 41313.0, 48593.0, 42641.0, 54242.0, 61078.0, 38240.0, 79386.0, 32281.0, 34888.0, 51668.0, 54054.0, 59521.0, 57679.0, 39529.0, 48225.0, 47568.0, 46593.0, 46655.0, 46752.0, 36640.0, 50859.0, 58207.0, 65724.0, 84871.0, 62368.0, 52550.0, 52419.0, 49963.0, 53293.0, 69651.0, 65925.0, 93514.0, 62350.0, 56947.0, 52213.0, 40563.0, 63456.0, 39939.0, 76125.0, 77024.0, 131813.0, 54286.0, 46218.0, 51502.0, 53058.0, 95899.0, 75697.0, 51238.0, 66965.0, 52367.0, 59396.0, 55549.0, 88535.0, 79369.0, 65157.0, 50928.0, 60505.0, 60523.0, 52164.0, 44338.0, 71325.0, 80614.0, 77318.0, 51820.0, 53848.0, 81178.0, 58227.0, 52539.0, 56647.0, 74574.0, 58061.0, 60448.0, 61753.0, 62769.0, 53258.0, 64669.0, 61367.0, 52406.0, 47078.0, 62637.0, 67498.0, 57874.0, 111883.0, 66687.0, 55330.0, 67139.0, 71253.0, 58191.0, 57351.0, 79087.0, 76334.0, 54779.0, 48750.0, 64716.0, 63207.0, 59259.0, 68049.0, 78605.0, 62671.0, 62686.0, 60965.0, 59472.0, 68968.0, 61351.0, 91874.0, 108590.0, 67266.0, 63250.0, 77933.0, 64352.0, 76919.0, 66386.0, 112538.0, 58872.0, 85816.0, 72068.0, 59272.0, 54827.0, 55864.0, 85232.0, 59818.0, 54874.0, 51952.0, 54074.0, 83002.0, 113282.0, 58242.0, 45380.0, 72527.0, 52781.0, 50662.0, 59476.0, 91312.0, 77917.0, 53658.0, 115519.0, 75729.0, 113372.0, 82748.0, 62833.0, 65495.0, 67740.0, 88842.0, 73236.0, 60020.0, 63353.0, 58886.0, 64145.0, 68713.0, 61389.0, 84182.0, 70310.0, 71939.0, 64723.0, 41628.0, 84203.0, 79130.0, 60324.0, 53063.0, 70017.0, 72921.0, 41835.0, 69776.0, 60436.0, 43488.0, 58373.0, 66341.0, 66403.0, 74905.0, 88328.0, 30305.0, 68011.0, 78561.0, 52050.0, 62616.0, 96058.0, 77894.0, 83648.0, 57472.0, 56719.0, 89427.0, 67652.0, 81370.0, 80804.0, 48703.0, 58793.0, 98311.0, 64802.0, 84133.0, 87197.0, 66409.0, 62639.0, 58523.0, 66273.0, 60309.0, 50184.0, 70594.0, 61281.0, 64336.0, 70456.0, 77868.0, 57422.0, 56927.0, 50709.0, 65444.0, 66256.0, 80304.0, 71430.0, 81850.0, 57774.0, 73730.0, 57799.0, 53203.0, 58555.0, 52192.0, 63560.0, 56933.0, 58809.0, 59955.0, 49169.0, 45570.0, 58756.0, 58319.0, 63250.0, 104752.0, 79406.0, 73235.0, 81583.0, 92950.0, 77491.0, 61818.0, 41151.0, 42822.0, 85313.0, 46791.0, 93796.0, 54010.0, 51766.0, 57346.0, 44644.0, 41671.0, 63540.0, 49190.0, 43702.0, 72718.0, 115722.0, 60888.0, 50194.0, 77800.0, 51687.0, 60516.0, 51898.0, 50433.0, 65028.0, 46511.0, 50979.0, 57711.0, 37280.0, 50256.0, 54650.0, 60011.0, 47821.0, 57606.0, 56996.0, 45777.0, 81033.0, 65370.0, 51594.0, 50812.0, 42023.0, 75943.0, 48447.0, 61925.0, 51163.0, 49668.0, 57619.0, 70176.0, 59521.0, 41272.0, 49227.0, 44468.0, 92943.0, 36684.0, 58916.0, 56396.0, 54667.0, 59571.0, 59388.0, 65398.0, 54027.0, 56408.0, 69563.0, 67679.0, 42326.0, 52034.0, 62809.0, 35735.0, 59855.0, 72441.0, 59094.0, 49053.0, 54998.0, 59121.0, 94237.0, 60679.0, 42843.0, 74804.0, 72188.0, 49508.0, 41829.0, 37132.0, 61322.0, 41994.0, 78870.0, 46468.0, 62838.0, 60876.0, 68805.0, 52647.0, 52304.0, 67580.0, 56839.0, 57786.0, 80027.0, 57903.0, 55959.0, 51485.0, 64527.0, 71303.0, 70785.0, 79807.0, 57955.0, 53516.0, 61602.0, 50429.0, 51715.0, 61640.0, 72080.0, 70682.0, 70528.0, 54483.0, 58068.0, 50129.0, 49762.0, 63797.0, 66084.0, 73605.0, 63410.0, 45958.0, 52364.0, 54622.0, 57840.0, 62601.0, 71477.0, 56047.0, 62310.0, 60691.0, 48413.0, 54402.0, 53649.0, 44913.0, 49961.0, 50752.0, 51228.0, 67575.0, 56708.0, 65492.0, 49999.0, 64450.0, 73280.0, 54666.0, 53237.0, 42786.0, 56329.0, 45678.0, 57954.0, 79396.0, 55565.0, 35230.0, 69145.0, 57262.0, 81180.0, 59969.0, 87138.0, 71799.0, 62174.0, 59521.0, 62363.0, 62060.0, 80459.0, 44518.0, 52911.0, 65093.0, 48593.0, 54450.0, 54346.0, 46074.0, 57502.0, 56294.0, 74078.0, 67275.0, 60044.0, 57476.0, 96035.0, 67381.0, 132971.0, 67546.0, 52318.0, 65078.0, 55964.0, 49989.0, 54681.0, 67139.0, 91041.0, 74665.0, 56971.0, 54681.0, 66236.0, 74391.0, 65497.0, 53795.0, 72658.0, 89170.0, 64523.0, 82892.0, 72836.0, 57450.0, 55079.0, 46043.0, 67122.0, 55608.0, 57880.0, 70254.0, 91758.0, 44774.0, 63570.0, 101748.0, 50871.0, 57353.0, 60125.0, 57293.0, 58620.0, 57515.0, 69973.0, 42582.0, 67097.0, 62211.0, 65650.0, 72633.0, 76659.0, 58509.0, 31901.0, 38846.0, 124586.0, 48513.0, 73701.0, 53024.0, 70755.0, 59674.0, 73068.0, 84010.0, 56796.0, 79409.0, 53942.0, 59882.0, 57301.0, 58506.0, 65618.0, 67232.0, 51262.0, 87195.0, 65033.0, 45455.0, 104228.0, 66045.0, 59019.0, 64804.0, 54065.0, 80946.0, 69197.0, 54180.0, 65789.0, 94678.0, 90592.0, 54530.0, 83143.0, 59430.0, 73243.0, 56554.0, 68129.0, 70451.0, 36818.0, 36436.0, 55541.0, 54684.0, 41293.0, 46177.0, 52228.0, 58354.0, 74517.0, 43925.0, 75142.0, 35371.0, 47935.0, 40332.0, 52308.0, 44925.0, 48305.0, 52141.0, 64492.0, 47003.0, 51758.0, 39972.0, 50324.0, 44607.0, 57042.0, 53299.0, 49235.0, 67741.0, 52398.0, 46691.0, 55994.0, 36170.0, 48693.0, 65763.0, 65005.0, 48243.0, 63160.0, 64461.0, 57208.0, 53841.0, 53116.0, 87878.0, 63042.0, 58903.0, 62334.0, 52456.0, 73191.0, 56202.0, 62152.0, 51604.0, 53936.0, 68058.0, 58091.0, 63007.0, 53033.0, 58830.0, 43472.0, 50701.0, 42004.0, 61394.0, 38716.0, 59521.0, 47559.0, 69633.0, 46181.0, 49454.0, 57507.0, 54525.0, 65427.0, 63966.0, 58282.0, 53707.0, 57377.0, 67631.0, 47898.0, 53808.0, 57413.0, 64175.0, 51271.0, 60152.0, 101204.0, 59305.0, 54923.0, 48934.0, 57361.0, 69608.0, 64701.0, 59765.0, 59308.0, 47383.0, 61870.0, 48425.0, 48048.0, 57494.0, 53769.0, 62310.0, 59865.0, 60550.0, 57364.0, 68091.0, 50567.0, 59521.0, 63004.0, 40867.0, 66816.0, 50288.0, 65664.0, 57061.0, 61024.0, 48273.0, 62250.0, 40684.0, 58743.0, 55876.0, 53888.0, 59521.0, 60602.0, 110080.0, 59999.0, 66137.0, 57044.0, 58631.0, 58545.0, 95051.0, 46199.0, 59994.0, 55013.0, 58786.0, 55144.0, 49811.0, 57758.0, 56982.0, 76234.0, 79176.0, 79115.0, 76497.0, 58771.0, 68633.0, 76188.0, 43887.0, 56629.0, 63864.0, 60333.0, 55112.0, 66144.0, 57671.0, 64179.0, 67249.0, 56530.0, 55166.0, 39988.0, 77018.0, 59521.0, 49128.0, 75345.0, 72401.0, 38899.0, 71587.0, 71188.0, 75909.0, 60903.0, 29415.0, 56249.0, 62009.0, 59911.0, 53206.0, 55722.0, 80445.0, 56558.0, 62140.0, 47079.0, 60150.0, 46725.0, 78425.0, 71699.0, 61865.0, 44151.0, 70627.0, 57700.0, 54005.0, 60701.0, 51402.0, 59661.0, 74242.0, 52371.0, 64472.0, 57832.0, 61824.0, 50675.0, 84260.0, 56840.0, 65784.0, 44267.0, 52366.0, 47686.0, 85647.0, 64703.0, 91448.0, 75027.0, 51739.0, 50840.0, 50183.0, 100514.0, 63444.0, 40939.0, 60781.0, 44424.0, 80896.0, 62898.0, 58404.0, 63671.0, 59684.0, 71704.0, 70115.0, 79426.0, 68868.0, 73467.0, 82515.0, 58560.0, 56804.0, 61291.0, 59521.0, 52582.0, 61729.0, 68945.0, 45035.0, 51173.0, 52884.0, 54141.0, 62274.0, 55251.0, 44688.0, 48985.0, 55915.0, 64952.0, 54632.0, 67760.0, 77238.0, 48801.0, 66639.0, 59751.0, 63361.0, 68625.0, 66716.0, 51503.0, 49529.0, 65859.0, 80228.0, 42304.0, 90607.0, 54418.0, 44714.0, 50210.0, 58944.0, 69675.0, 58704.0, 60838.0, 54344.0, 60184.0, 57728.0, 59730.0, 55184.0, 64234.0, 50018.0, 78974.0, 62480.0, 70899.0, 54923.0, 51548.0, 61749.0, 59521.0, 37996.0, 22917.0, 31246.0, 60661.0, 27811.0, 59521.0, 29751.0, 29023.0, 28262.0, 26098.0, 31592.0, 23825.0, 37728.0, 29403.0, 27079.0, 33732.0, 29117.0, 30977.0, 35322.0, 28995.0, 32963.0, 33230.0, 51164.0, 29384.0, 36313.0, 28676.0, 35718.0, 69903.0, 33439.0, 50834.0, 136959.0, 81751.0, 52900.0, 55200.0, 31926.0, 74838.0, 43848.0, 54762.0, 67891.0, 35271.0, 35490.0, 51307.0, 29712.0, 107963.0, 59470.0, 47825.0, 53646.0, 70545.0, 62324.0, 84333.0, 32138.0, 38251.0, 70838.0, 120258.0, 87445.0, 47702.0, 59369.0, 46846.0, 44376.0, 73626.0, 59304.0, 126895.0, 62191.0, 52778.0, 110100.0, 93273.0, 59521.0, 50399.0, 65410.0, 59489.0, 44055.0, 33938.0, 55281.0, 56872.0, 38089.0, 70107.0, 97872.0, 36048.0, 80589.0, 97262.0, 82068.0, 46288.0, 67614.0, 55112.0, 49547.0, 59521.0, 40588.0, 66210.0, 79486.0, 62546.0, 62068.0, 55974.0, 61486.0, 68306.0, 55216.0, 62950.0, 52812.0, 73337.0, 58676.0, 54553.0

In [78]:
college_df.head()

,Unique Institutional ID,Institution Name,State,Region,Campus Urbanization Type,Institutional Control,Admission Rate,Avearge SAT Score,Average ACT Midpoint,Undergarduate Enrollment,...,Full-Time Retention Rate,Four-Year Institution Graduation Rate,Median Graduate Debt,Median Earnings 4 Years Post-Graduation,Median Earnings 10 Years Post-Graduation,Admission Rate (median),Average Cost of Attendance (median),Full-Time Retention Rate (median),Four-Year Institution Graduation Rate (median),Median Earnings 4 Years Post-Graduation (median)
0,100654,Alabama A & M University,AL,5,12.0,1,0.579500,938.0,18.0,6124.0,...,0.698900,0.2403,31000.0,54018.0,40628.0,0.5795,27153.0,0.6989,0.2403,54018.0
1,100663,University of Alabama at Birmingham,AL,5,12.0,1,0.881800,1258.0,27.0,11635.0,...,0.800900,0.6423,22300.0,64969.0,54501.0,0.8818,28145.0,0.8009,0.6423,64969.0
2,100690,Amridge University,AL,5,12.0,2,0.712014,Test Optional,Test Optional,241.0,...,0.751822,1.0000,32189.0,50075.0,37621.0,0.7606,40404.0,0.7628,1.0000,50075.0
3,100706,University of Alabama in Huntsville,AL,5,12.0,1,0.685700,1319.0,28.0,6591.0,...,0.842500,0.6429,20705.0,81045.0,61767.0,0.6857,27392.0,0.8425,0.6429,81045.0
4,100724,Alabama State University,AL,5,12.0,1,0.975500,976.0,18.0,3477.0,...,0.697500,0.3034,31000.0,45998.0,34502.0,0.9755,23586.0,0.6975,0.3034,45998.0